In [1]:
import sys
import os
os.chdir("../")

import pandas as pd
import matplotlib
import data

In [2]:
train_df = data.train_df('full')

In [3]:
train_df.head(10)

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
0,008UN2RY0DMY,cd10940538005,1541031243,1,search for destination,"Rochester, USA",US,"Rochester, USA",desktop,NaN,NaN,NaN
1,008UN2RY0DMY,cd10940538005,1541031463,2,change of sort order,interaction sort button,US,"Rochester, USA",desktop,NaN,NaN,NaN
2,008UN2RY0DMY,cd10940538005,1541031473,3,change of sort order,distance and recommended,US,"Rochester, USA",desktop,NaN,NaN,NaN
3,008UN2RY0DMY,cd10940538005,1541031473,4,filter selection,Focus on Distance,US,"Rochester, USA",desktop,Focus on Distance,NaN,NaN
4,008UN2RY0DMY,cd10940538005,1541031550,5,interaction item image,57103,US,"Rochester, USA",desktop,NaN,NaN,NaN
5,008UN2RY0DMY,cd10940538005,1541031550,6,interaction item image,57103,US,"Rochester, USA",desktop,NaN,NaN,NaN
6,008UN2RY0DMY,cd10940538005,1541031560,7,interaction item image,57103,US,"Rochester, USA",desktop,NaN,NaN,NaN
7,008UN2RY0DMY,cd10940538005,1541031560,8,interaction item image,57103,US,"Rochester, USA",desktop,NaN,NaN,NaN
8,008UN2RY0DMY,cd10940538005,1541031570,9,interaction item image,57103,US,"Rochester, USA",desktop,NaN,NaN,NaN
9,008UN2RY0DMY,cd10940538005,1541031570,10,interaction item image,57103,US,"Rochester, USA",desktop,NaN,NaN,NaN

## Sessions per user

In [4]:
user_sessions_group = train_df[['user_id','session_id']].groupby('user_id').agg('count').sort_values('session_id', ascending=False)

In [6]:
h = user_sessions_group.hist(bins=200)
h.set_xscale('log')

AttributeError: 'numpy.ndarray' object has no attribute 'set_xscale'

### 80% of users in train have more then

In [12]:
len(user_sessions_group[user_sessions_group['session_id'] > 1])/len(user_sessions_group)

0.8043330418731176