In [1]:
import pandas as pd
df = pd.read_csv("../dataset/preprocessed/full.csv")

In [2]:
# Si prendono le righe che hanno reference non nulla e il campo 'city' non nullo. Si eliminano i 
# le righe che hanno la stessa tripletta ['session_id','reference','city']
mask = df['reference'].notnull() &(df['reference'].dtype != 'str') & (df['city'].notnull())
df_locations = df[mask]
df_locations = df_locations[['session_id','reference','city']].drop_duplicates()
df_locations = df_locations[df_locations['reference'].str.isnumeric() == True]

In [3]:
df_city = df_locations.groupby('city')['reference'].apply(lambda x: list(x))
df_city

city
's-Heerenberg, Netherlands                              [2010379, 53248, 53248, 2725638]
's-Hertogenbosch, Netherlands          [444516, 1387386, 4828612, 775223, 444516, 444...
100 Mile House, Canada                 [8163644, 8163644, 43791, 116043, 116043, 9954...
100 Mile Ranch, Canada                                                         [5210050]
10th of Ramadan City, Egypt                                                    [2431048]
25 de mayo, Argentina                               [8871972, 8871972, 8871972, 8871972]
6th of October City, Egypt             [4751702, 3477558, 92439, 1586313, 6267874, 55...
A Lama, Spain                                                                  [1786927]
A Pontenova, Spain                                             [185806, 949561, 6988358]
A Teixeira, Spain                                                              [1869767]
Aabenraa, Denmark                      [4044844, 1286666, 4044844, 54002, 4065276, 31...
Aachen, Germany                        [6279, 5066006, 13684, 52112, 147183, 6283, 62...
Aadorf, Switzerland                                                            [3990666]
Aagtekerke, Netherlands                                               [6979982, 2258566]
Aalborg, Denmark                       [1319941, 1319941, 98996, 98996, 53866, 53932,...
Aalen, Germany                         [2282638, 1292041, 14363, 14363, 14363, 33018,...
Aalsmeer, Netherlands                  [2707560, 106242, 9773310, 2707560, 105703, 10...
Aalst, Belgium                         [4487872, 3918952, 15027, 33199, 1560439, 1556...
Aalst, Netherlands                                                    [2803260, 4485784]
Aalten, Netherlands                                           [1970617, 1970617, 750911]
Aalter, Belgium                        [931363, 1770511, 137257, 6032852, 921369, 107...
Aarau, Switzerland                     [2404752, 4837772, 24498, 40983, 24498, 901109...
Aarberg, Switzerland                                             [24876, 24864, 2180062]
Aarburg, Switzerland                                                           [1692735]
Aardenburg, Netherlands                [4514134, 4514134, 4514134, 4514134, 13873, 23...
Aarhus, Denmark                        [53910, 378326, 53865, 378326, 5818832, 54000,...
Aars, Denmark                                      [86422, 1884645, 86420, 86422, 86422]
Aarschot, Belgium                                                              [1890773]
Aartselaar, Belgium                                                            [1064254]
Abadiânia, Brazil                      [9846168, 9470458, 10017576, 9605086, 9605086,...
                                                             ...
Škofja Loka, Slovenia                                        [2365814, 2365814, 4098666]
Šmarje pri Jelšah, Slovenia                                                    [9216706]
Šolta, Croatia                                               [4068044, 3995232, 4055490]
Špania Dolina, Slovakia                                                [991841, 2790222]
Špindleruv Mlýn, Czech Republic        [1306490, 119939, 1566869, 128073, 2807510, 11...
Štetí, Czech Republic                                                          [2302590]
Štramberk, Czech Republic                                                      [4803572]
Štrba, Slovakia                        [3945542, 2345272, 3988934, 1406520, 1566057, ...
Štrbské Pleso, Slovakia                [955015, 1566057, 1406520, 1182060, 2029127, 1...
Štrpce, Kosovo                                                                 [8124416]
Štúrovo, Slovakia                      [5527550, 8191712, 9474024, 2672602, 5525576, ...
Šumperk, Czech Republic                [3164307, 2641032, 5114762, 2782352, 5512520, ...
Švihov, Czech Republic                                                         [4599690]
Żabia Wola, Poland                                                             [1319136]
Żarki, Poland                          [7707418, 5118336, 3979914, 4964144, 1041382, ...
Żarnów, Poland                                      [4143196, 4143196, 4501510, 4143196]
Żebbuġ, Malta                              [4645644, 3225218, 8106080, 6100380, 9477854]
Żelechów, Poland                       [2705185, 1970193, 2705185, 2705185, 2705185, ...
Żurrieq, Malta                                                                 [7139110]
Žabljak, Montenegro                    [3943636, 3943636, 3065058, 3943636, 5453840, ...
Žagubica, Serbia                           [9159422, 4637492, 9255424, 9159422, 4637492]
Žalec, Slovenia                                                       [7381656, 1950281]
Žarnovica, Slovakia                                          [2313356, 2248320, 4720864]
Ždiar, Slovakia                        [2641244, 2755316, 6704502, 607876, 2641532, 7...
Žiar nad Hronom, Slovakia                                                      [9696742]
Žilina, Slovakia                       [4923998, 2579620, 3218920, 764798, 3873334, 1...
Živogošće, Croatia                     [4266724, 5188048, 5866666, 4266724, 9655950, ...
Župa dubrovačka, Croatia                                                       [1822969]
Șimian, Romania                                                                [4077698]
Κato Platres - Pano Platres, Cyprus                              [3519812, 33805, 33802]
Name: reference, Length: 34326, dtype: object

In [4]:
from collections import Counter

In [5]:
# Si ordinano le accomodation in base alla frequenza in una città
df_city_occurrencies = pd.concat([pd.DataFrame([[index, dict(Counter(value).most_common())]], columns=['city', 'occurrencies']) for index, value in df_city.iteritems()], ignore_index=True)
#df_city_occurrencies

,city,occurrencies
0,"'s-Heerenberg, Netherlands","{'53248': 2, '2010379': 1, '2725638': 1}"
1,"'s-Hertogenbosch, Netherlands","{'163255': 22, '775223': 21, '444516': 18, '10..."
2,"100 Mile House, Canada","{'116043': 3, '8163644': 2, '44223': 2, '43791..."
3,"100 Mile Ranch, Canada",{'5210050': 1}
4,"10th of Ramadan City, Egypt",{'2431048': 1}
5,"25 de mayo, Argentina",{'8871972': 4}
6,"6th of October City, Egypt","{'55288': 5, '92439': 2, '1586313': 2, '626787..."
7,"A Lama, Spain",{'1786927': 1}
8,"A Pontenova, Spain","{'185806': 1, '949561': 1, '6988358': 1}"
9,"A Teixeira, Spain",{'1869767': 1}
10,"Aabenraa, Denmark","{'3112808': 5, '53948': 4, '54002': 3, '404484..."
11,"Aachen, Germany","{'5066006': 60, '17966': 51, '6267': 43, '6265..."
12,"Aadorf, Switzerland",{'3990666': 1}
13,"Aagtekerke, Netherlands","{'6979982': 1, '2258566': 1}"
14,"Aalborg, Denmark","{'1319941': 24, '98996': 23, '2125964': 14, '3..."
15,"Aalen, Germany","{'14363': 13, '1292041': 4, '2282638': 3, '406..."
16,"Aalsmeer, Netherlands","{'2707560': 6, '106242': 3, '105703': 3, '9773..."
17,"Aalst, Belgium","{'1560439': 7, '3918952': 5, '33199': 5, '4487..."
18,"Aalst, Netherlands","{'2803260': 1, '4485784': 1}"
19,"Aalten, Netherlands","{'1970617': 2, '750911': 1}"
20,"Aalter, Belgium","{'931363': 1, '1770511': 1, '137257': 1, '6032..."
21,"Aarau, Switzerland","{'24498': 5, '2404752': 1, '4837772': 1, '4098..."
22,"Aarberg, Switzerland","{'24876': 1, '24864': 1, '2180062': 1}"
23,"Aarburg, Switzerland",{'1692735': 1}
24,"Aardenburg, Netherlands","{'4514134': 11, '2345014': 2, '13873': 1, '541..."
25,"Aarhus, Denmark","{'378326': 34, '5818832': 34, '53842': 26, '53..."
26,"Aars, Denmark","{'86422': 3, '1884645': 1, '86420': 1}"
27,"Aarschot, Belgium",{'1890773': 1}
28,"Aartselaar, Belgium",{'1064254': 1}
29,"Abadiânia, Brazil","{'9605086': 7, '7132566': 3, '9846168': 2, '94..."
...,...,...
34296,"Škofja Loka, Slovenia","{'2365814': 2, '4098666': 1}"
34297,"Šmarje pri Jelšah, Slovenia",{'9216706': 1}
34298,"Šolta, Croatia","{'4068044': 1, '3995232': 1, '4055490': 1}"
34299,"Špania Dolina, Slovakia","{'991841': 1, '2790222': 1}"
34300,"Špindleruv Mlýn, Czech Republic","{'116162': 21, '120759': 15, '113720': 14, '11..."
34301,"Štetí, Czech Republic",{'2302590': 1}
34302,"Štramberk, Czech Republic",{'4803572': 1}
34303,"Štrba, Slovakia","{'1406520': 2, '3945542': 1, '2345272': 1, '39..."
34304,"Štrbské Pleso, Slovakia","{'1182060': 17, '1566057': 13, '1406520': 13, ..."
34305,"Štrpce, Kosovo",{'8124416': 1}
34306,"Štúrovo, Slovakia","{'2640330': 3, '8191712': 2, '3443802': 2, '55..."
34307,"Šumperk, Czech Republic","{'3164307': 1, '2641032': 1, '5114762': 1, '27..."
34308,"Švihov, Czech Republic",{'4599690': 1}
34309,"Żabia Wola, Poland",{'1319136': 1}
34310,"Żarki, Poland","{'7707418': 1, '5118336': 1, '3979914': 1, '49..."
34311,"Żarnów, Poland","{'4143196': 3, '4501510': 1}"
34312,"Żebbuġ, Malta","{'4645644': 1, '3225218': 1, '8106080': 1, '61..."
34313,"Żelechów, Poland","{'2705185': 5, '1970193': 2, '9789568': 1}"
34314,"Żurrieq, Malta",{'7139110': 1}
34315,"Žabljak, Montenegro","{'3943636': 14, '5453840': 4, '7778606': 3, '1..."
34316,"Žagubica, Serbia","{'9159422': 2, '4637492': 2, '9255424': 1}"
34317,"Žalec, Slovenia","{'7381656': 1, '1950281': 1}"
34318,"Žarnovica, Slovakia","{'2313356': 1, '2248320': 1, '4720864': 1}"
34319,"Ždiar, Slovakia","{'2755316': 10, '2029775': 4, '7806470': 3, '2..."
34320,"Žiar nad Hronom, Slovakia",{'9696742': 1}
34321,"Žilina, Slovakia","{'2579620': 9, '3986876': 9, '3218920': 6, '20..."
34322,"Živogošće, Croatia","{'4266724': 3, '5188048': 1, '5866666': 1, '96..."
34323,"Župa dubrovačka, Croatia",{'1822969': 1}
34324,"Șimian, Romania",{'4077698': 1}
34325,"Κato Platres - Pano Platres, Cyprus","{'3519812': 1, '33805': 1, '33802': 1}"

In [6]:
df_test = pd.read_csv("/Users/claudiorussointroito/Documents/GitHub/recsysTrivago2019/dataset/original/test.csv")

In [7]:
import math

In [8]:
def get_submission_target(df):
    """Identify target rows with missing click outs."""

    mask = df["reference"].isnull() & (df["action_type"] == "clickout item")
    df_out = df[mask]

    return df_out

def string_to_array(s):
    """Convert pipe separated string to array."""

    if isinstance(s, str):
        out = s.split("|")
    elif math.isnan(s):
        out = []
    else:
        raise ValueError("Value must be either string of nan")
    return out

In [64]:
# Submission considerando tutti i clickout del test e ordinandoli in base alla popolarità di 
# un'accomodation in quella città. Score: 0.324485
df_target = get_submission_target(df_test)

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
6,004A07DM0IDW,1d688ec168932,1541555799,7,clickout item,NaN,CO,"Santa Marta, Colombia",mobile,NaN,2059240|2033381|1724779|127131|399441|103357|1...,70|46|48|76|65|65|106|66|87|43|52|44|60|61|50|...
8,009RGHI3G9A3,f05ab0de907e2,1541570940,2,clickout item,NaN,IN,"Nathdwara, India",mobile,NaN,10884872|7065316,64|28
10,00Y1Z24X8084,26b6d294d66e7,1541651823,2,clickout item,NaN,PH,"Iloilo City, Philippines",mobile,NaN,2714480|4476010|3843244|3833012|9017890|198100...,74|14|22|38|55|44|28|34|23|27|12|108|19|21|36|...
15,01V3WDTDM5CU,07628a0f5be0b,1541575643,5,clickout item,NaN,PL,"Wisla, Poland",mobile,Sort by Price,3565720|2947584|4115018|2039671|3836538|801409...,16|18|20|21|22|22|28|28|28|30|30|33|33|35|35|3...
61,02AOAVF9PVYH,4a01c3afbc224,1541681278,46,clickout item,NaN,JP,"Yokohama, Japan",desktop,Hotel|Resort|Sort by Price,1451247|559056|1045096|1963879|693596|1967173|...,80|81|81|82|82|82|83|83|83|85|85|88|88|91|92|9...
109,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,13361|5647680|116764|898719|8276346|9168|19325...,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...
111,0386OH8JDE1Q,e09591d07cdef,1541620536,2,clickout item,NaN,UK,"John o' Groats, United Kingdom",desktop,NaN,1193320|5488246|3858774|4552034|10620372|22696...,103|88|100|134|109|138|126|86
115,03LTH89QY623,7663406cf586c,1541554183,4,clickout item,NaN,CA,"Koloa, USA",desktop,NaN,241961|906477|991561|353701|1149665|77258|4943...,287|300|261|197|163|263|262|188|540|283|211|22...
138,03VT0ODUTZB0,725e8adf70e86,1541632490,23,clickout item,NaN,UK,"Warrington, United Kingdom",desktop,NaN,109938|164193|632366|1362450|1070666|164220|11...,45|67|78|60|58|57|86|68|57|55|148|92|66|55|61|...
314,03XH0JWCWHAM,73f4c417ff730,1541566143,176,clickout item,NaN,MX,"Puebla, Mexico",mobile,Sort By Popularity,42692|5116230|42876|4342578|42864|3148690|2123...,53|181|60|45|96|60|80|59|41|122|50|43|113|48|5...
319,05BAHQHA5RCI,9f279162e8d5c,1541633993,5,clickout item,NaN,DE,"Ulm, Germany",tablet,Best Value,2755290|14054|10243166|3498770|726906|2616752|...,59|86|70|58|86|58|58|57|78|68|55|90|79|64|112|...
340,062OG5L9831R,289b34a2bb4dd,1541663105,21,clickout item,NaN,TR,"Sigacik, Turkey",desktop,NaN,5828606|6618430|7828086|8474478|9225478|991468...,45|44|51|40|28|50|43|28|26|46|30|27|55|110|44|...
354,06OT6WXN246O,ca92389e5ea65,1541688448,14,clickout item,NaN,KR,"Namhae, South Korea",desktop,NaN,4667086|3152528|5480450|4341286|5601476|397494...,132|63|78|115|78|110|117|56|127|78|70|180|133|...
384,08GEUYKFOOPX,83ce8ea2a61b4,1541643155,30,clickout item,NaN,MY,"Malacca, Malaysia",mobile,NaN,3818266|2547593|3899110|4599632|377921|508851|...,23|32|27|30|30|38|97|14|53|38|49|47|25|29|17|3...
447,091L4C793B1J,49816a95c986a,1541625659,63,clickout item,NaN,AR,"Bombinhas, Brazil",mobile,NaN,2504828|2578276|511676|2344190|1652507|3242334...,135|76|62|93|51|45|75|28|40|76|32|27|50|77|92|...
449,09K0CO8F5AXJ,ccaf5005ee842,1541693719,2,clickout item,NaN,DE,"Leipzig, Germany",desktop,NaN,6605|2270374|12959|6576|1622837|4122274|195595...,165|226|189|82|249|109|154|146|68|110|158|188|...
452,09X618WIVTP3,b1935d2a43d5e,1541688108,3,clickout item,NaN,MY,"Genting Highlands, Malaysia",mobile,NaN,1120687|2165594|5763948|519501|595286|3386520|...,39|76|78|55|87|38|47|143|57|53|21|8|78|17|59|1...
494,09YREZJA9YH3,572801ee070f0,1541688494,42,clickout item,NaN,TR,"Kozakli, Turkey",mobile,NaN,2032775|491891|1886115|3877836|5723470|4493250...,27|24|50|37|27|53|56|40|40|18|40|42|25|24|21|4...
510,0A30V2M11MDK,dc8ded19d1781,1541689101,16,clickout item,NaN,NL,"Paris, France",desktop,Hotel Chain|Focus on Distance|Satisfactory Rating,362746|48572|48885|49747|48426|50136|85862|496...,78|62|69|74|91|74|77|113|70|79|91|80|91|106|11...
512,0A8YWBYRBRTP,d29141ddbd43f,1541623589,2,clickout item,NaN,CA,"Ottawa, Canada",desktop,NaN,43495|43652|44038|43503|44682|43765|43359|4361...,109|106|106|119|89|141|103|93|89|93|81|106|126...
513,0BZN2KFMHLZF,d9497eeb946dc,1541668916,1,clickout item,NaN,BE,"Hasselt, Belgium",mobile,NaN,39730|133101|39758|7029236|455086|3887112|1070...,90|88|80|80|90|62|65|90|89|75|70|109|165|104|6...
546,0CN5A7BJZRGW,0b105be325b12,1541657496,33,clickout item,NaN,IN,"Bengaluru, India",desktop,NaN,998041|1389106|1400686|2216204|2394112|2817576...,11|47|23|19|12|8|16|16|23|16|18|19|15|22|103|2...
553,0D1M41K80XJ1,7567cae385981,1541660443,7,clickout item,NaN,HK,"Macau, China",desktop,NaN,2269838|1439759|211041|1833415|1331323|923995|...,114|142|188|144|146|104|96|107|135|90|81|137|1...
554,0D1XFBRWUX7Z,35e873299a45f,1541586069,1,clickout item,NaN,AU,"Sydney, Australia",mobile,NaN,54865|54803|54953|14211|95510|54838|54794|1484...,163|126|158|177|145|85|107|158|132|189|187|131...
594,0DHC2FF92LFS,b4b881ddb91e0,1541601665,40,clickout item,NaN,AU,"Lorne, Australia",mobile,NaN,109119|109118|1018349|2846590|1885413|2941498|...,145|131|108|86|83|222|72|140|111|92|121|32|114...
597,0DJUQ92EQYM0,d2039eb924c5d,1541649689,3,clickout item,NaN,BR,"Águas Claras, Brazil",mobile,NaN,3145586|5157920|478986|3993110|478991|5790206|...,44|26|30|43|45|37|17|42|17|25|27|22|44|33|22|3...
598,0EPVF4QE049Q,11b583578f7f3,1541611766,1,clickout item,NaN,FI,"Seinäjoki, Finland",mobile,NaN,368306|369426|4916202|2045589|1328820|369421|1...,123|152|59|148|105|147|98|70|95|80|140
599,0GY71I4BUBQW,334177bbc6525,1541638087,1,clickout item,NaN,AU,"Rome, Italy",desktop,NaN,17112|1374294|17382|2321776|16895|17056|17108|...,81|95|126|79|186|112|53|112|56|214|142|77|71|1...
600,0H2RFN3FXM5A,e9fa318e4aad0,1541576918,1,clickout item,NaN,IN,"Bengaluru, India",mobile,NaN,1984531|4775794|1400686|930783|2612414|1199716...,37|16|19|50|148|16|157|14|21|19|14|16|16|22|13...
602,0HG5FZNPFDYC,db55ce2d55626,1541571390,2,clickout item,NaN,RU,"Rostov-on-Don, Russia",mobile,NaN,10001880|6452708|7492016|1048438|10127018|4726...,54|205|40|52|187|34|39|29|70|46|39|69|36|55|55...
...,...,...,...,...,...,...,...,...,...,...,...,...
3781666,Z6S5ELLKWH9U,b4cb947d63b06,1541642593,1,clickout item,NaN,NL,"Kralendijk, BES Islands",mobile,NaN,6893878|30595|5963500|6931536|975701|30599|877...,156|204|83|120|160|362|142|211|75|161|169|99|9...
3781668,Z6UH43QKBEFA,1a185e56b1687,1541592222,2,clickout item,NaN,AR,"Florianópolis, Brazil",desktop,NaN,5088964|861491|104832|478996|1330207|1862179|2...,58|115|748|178|200|166|77|291|103|106|166|125|...
3781671,Z6UH5S6YCFGU,0de3309ea3315,1541625537,3,clickout item,NaN,US,"Las Vegas, USA",desktop,NaN,2793224|8621|1810141|32727|77124|893925|8518|2...,182|278|764|182|139|108|273|174|106|111|244|14...
3781673,Z7H6WZBWLCXT,5d6cc2ee3db46,1541631030,2,clickout item,NaN,BR,"Fortaleza, Brazil",mobile,NaN,104802|5032060|104867|104773|104939|104505|104...,71|99|98|89|139|70|90|103|115|86|113|89|48|53|...
3781687,Z8R3PNWG66WC,037d21739ccad,1541672836,14,clickout item,NaN,IT,"Amsterdam, Netherlands",mobile,NaN,1719593|3152692|4345706|3154396|42101|147253|1...,756|1177|254|986|962|724|169|534|690|310|359|2...
3781688,Z9GZ0O9E98XH,1694bed3ee9fb,1541667268,1,clickout item,NaN,AU,"Adelaide, Australia",desktop,NaN,667061|101857|995701|14848|3923476|54864|10923...,96|86|89|140|80|95|168|73|46|82|127|210|89|89|...
3781690,ZFD2YAQS3YX4,1e7237d9f35a8,1541709847,2,clickout item,NaN,BR,"São Paulo, Brazil",desktop,NaN,104912|5816566|478966|104607|104539|104710|597...,138|365|144|136|183|79|84|457|96|216|104|129|1...
3781706,ZG9YRVARN8VE,7cc8c6b3f4a97,1541714873,16,clickout item,NaN,PE,"Máncora, Peru",mobile,NaN,3215419|2828636|3066968|1796789|2441706|271802...,43|56|70|53|55|44|123|97|104|40|44|40|70|6|20|...
3781708,ZI483FNQTFE5,da06f0c5c4e27,1541664029,2,clickout item,NaN,IN,"Mumbai, India",mobile,NaN,4530384|9757680|9378320|99502|9661068|9618174|...,6|29|22|210|29|19|24|44|36|36|30|30|43|28|127|...
3781709,ZJDPHM5DWJCD,e1b43bf209d50,1541577899,1,clickout item,NaN,BE,"Grindelwald, Switzerland",mobile,NaN,15953|1362025|15233|15955|1008989|7300410|1410...,134|148|212|239|64|105|126|564|126|564|709|218...
3781718,ZKABS031TSS3,82a1d6694e8fd,1541687528,9,clickout item,NaN,US,"Ivins, USA",mobile,NaN,387646|10472726|381376|70720|70701|1082856|677...,314|131|61|128|144|79|117|34|91|42|69|148|130|...
3781722,ZLZR6ZVNT61X,86632d06943ef,1541686280,4,clickout item,NaN,RU,"Çolakli, Turkey",mobile,NaN,94540|13103|96162|863116|97628|1409690|486686|...,68|150|26|161|65|18|32|270|67|80|59|81|176|79|...
3781740,ZN0MI3V8DU6I,eec026e9dd8d9,1541560976,18,clickout item,NaN,US,"Vernon, USA",desktop,NaN,374956|620556|5964090|2506754|7846536|393276|2...,139|118|87|79|208|153|96|219|118
3781741,ZN7BDD39Y83X,929b6ba33334d,1541617907,1,clickout item,NaN,UK,"Glasgow, United Kingdom",mobile,NaN,152500|18512|627451|1061780|655466|2177802|123...,56|47|45|39|54|36|41|49|37|44|56|53|57|56|39|5...
3781755,ZOO280YM822I,d6a2d7a9d5711,1541554261,14,clickout item,NaN,TR,"Istanbul, Turkey",mobile,NaN,2773384|5587842|80224|1346904|80289|8301508|40...,33|41|33|31|35|35|42|40|32|26|39|36|42|33|21|3...
3781757,ZPII0N59F3R2,e341ad089f472,1541671799,2,clickout item,NaN,AU,"Reykjavík, Iceland",desktop,NaN,3757476|102361|6596362|104092|6299792|2081670|...,136|97|124|76|170|152|166|132|118|115|159|214|...
3781775,ZQDEMN3TBJ58,a60ba6624628a,1541639908,18,clickout item,NaN,BR,"Fortaleza, Brazil",desktop,NaN,104594|104867|104889|1162971|1201630|104888|10...,69|63|57|46|37|65|55|64|81|50|46|42|41|63|49|5...
3781776,ZT722F7KOKI8,66c459fc5f1d5,1541569655,1,clickout item,NaN,MX,"Chetumal, Mexico",mobile,NaN,2752786|42775|2777094|2028173|2637405|3140790|...,43|42|66|28|51|77|70|82|35|36|62|26|24|37|28|2...
3781780,ZU64EXB7HUSC,a12e64eb21788,1541618644,4,clickout item,NaN,US,"Victoria, Canada",desktop,NaN,44282|44410|44182|837166|1353966|44243|44679|4...,237|169|126|94|133|186|113|286|117|144|181|99|...
3781788,ZUCX42KNP5CA,911f86ae3cf64,1541678577,8,clickout item,NaN,JP,"Sasebo, Japan",desktop,Sort by Price,1738509|1738515|7689134|2018845|1179138|106494...,54|100|108|116|135|154|192|208|216|217|249|269...
3781790,ZV68634ROL49,4f5808cfa765b,1541699124,2,clickout item,NaN,IN,"Mussoorie, India",mobile,NaN,2841397|1005131|2378072|2378074|2643434|312778...,17|29|7|38|8|34|22|21|73|29|7|18|12|40|33|18|2...
3781839,ZVTSO44R1US2,ba077694ccf39,1541673409,49,clickout item,NaN,JP,"Sapporo, Japan",desktop,Hotel|Resort|Best Value|Hammam,5863172|494271|1042070|103453|9327438|2111024|...,72|90|100|92|81|86|92|83|81|100|105|104|95|87|...
3781840,ZVUSADAHBEMO,f5f4f9aa82b44,1541678661,1,clickout item,NaN,DE,"Grainau, Germany",desktop,NaN,51656|96015|52072|5465|5470|5484|117981|255274...,146|200|124|99|88|133|112|85|79|95|87|95|95|91...
3781844,ZWB59UGA2UUY,6f5d6ebfe10b5,1541558109,4,clickout item,NaN,MY,"Kuala Lumpur, Malaysia",desktop,NaN,101409|101389|101381|95870|3484802|101373|1945...,38|47|44|52|48|48|40|41|32|60|106|46|56|56|103...
3781846,ZWD4F2A7H5EK,3e4fdd55f6145,1541670697,2,clickout item,NaN,IT,"Milan, Italy",desktop,NaN,20259|20339|20363|20400|20407|954207|20564|202...,77|73|77|66|84|22|86|76|77|78|81|74|94|84|74|7...
3782317,ZXGCLNDBW84E,e73c90b6f448e,1541699269,466,clickout item,NaN,BR,"Porto Seguro, Brazil",desktop,NaN,916029|1650015|326846|503361|1326068|477936|38...,60|81|140|171|49|42|38|60|57|74|191|71|55|45|5...
3782325,ZYG4MMKT847V,0f128fd98b4e3,1541634384,4,clickout item,NaN,BR,"Resende, Brazil",mobile,NaN,1089752|4103676|2033145|2684451|2053814|279089...,86|82|86|40|92|56|83|54|145|114|58|67|40|87|46...
3782327,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,clickout item,NaN,US,"Holiday City, USA",mobile,NaN,364796|1299248|4891790|381296|1345175|9647370,92|52|92|89|59|275
3782333,ZZ39YE45SZIE,f5db4092ec9fc,1541551945,6,clickout item,NaN,HK,"Taitung City, Taiwan",mobile,NaN,9925140|2625125|5779140|7365168|5849342|198775...,219|215|183|215|590|70|131|111|64|65|127|94|64...
3782334,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,46149|109974|46119|8333280|12455|1185556|84002...,138|138|156|153|128|202|145|137|105|68|133|167...

In [11]:
df_target_copy = df_target.copy()
df_target_copy.loc[:,'impressions'] = df_target_copy['impressions'].apply(string_to_array)

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
6,004A07DM0IDW,1d688ec168932,1541555799,7,clickout item,NaN,CO,"Santa Marta, Colombia",mobile,NaN,"[2059240, 2033381, 1724779, 127131, 399441, 10...",70|46|48|76|65|65|106|66|87|43|52|44|60|61|50|...
8,009RGHI3G9A3,f05ab0de907e2,1541570940,2,clickout item,NaN,IN,"Nathdwara, India",mobile,NaN,"[10884872, 7065316]",64|28
10,00Y1Z24X8084,26b6d294d66e7,1541651823,2,clickout item,NaN,PH,"Iloilo City, Philippines",mobile,NaN,"[2714480, 4476010, 3843244, 3833012, 9017890, ...",74|14|22|38|55|44|28|34|23|27|12|108|19|21|36|...
15,01V3WDTDM5CU,07628a0f5be0b,1541575643,5,clickout item,NaN,PL,"Wisla, Poland",mobile,Sort by Price,"[3565720, 2947584, 4115018, 2039671, 3836538, ...",16|18|20|21|22|22|28|28|28|30|30|33|33|35|35|3...
61,02AOAVF9PVYH,4a01c3afbc224,1541681278,46,clickout item,NaN,JP,"Yokohama, Japan",desktop,Hotel|Resort|Sort by Price,"[1451247, 559056, 1045096, 1963879, 693596, 19...",80|81|81|82|82|82|83|83|83|85|85|88|88|91|92|9...
109,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,"[13361, 5647680, 116764, 898719, 8276346, 9168...",185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...
111,0386OH8JDE1Q,e09591d07cdef,1541620536,2,clickout item,NaN,UK,"John o' Groats, United Kingdom",desktop,NaN,"[1193320, 5488246, 3858774, 4552034, 10620372,...",103|88|100|134|109|138|126|86
115,03LTH89QY623,7663406cf586c,1541554183,4,clickout item,NaN,CA,"Koloa, USA",desktop,NaN,"[241961, 906477, 991561, 353701, 1149665, 7725...",287|300|261|197|163|263|262|188|540|283|211|22...
138,03VT0ODUTZB0,725e8adf70e86,1541632490,23,clickout item,NaN,UK,"Warrington, United Kingdom",desktop,NaN,"[109938, 164193, 632366, 1362450, 1070666, 164...",45|67|78|60|58|57|86|68|57|55|148|92|66|55|61|...
314,03XH0JWCWHAM,73f4c417ff730,1541566143,176,clickout item,NaN,MX,"Puebla, Mexico",mobile,Sort By Popularity,"[42692, 5116230, 42876, 4342578, 42864, 314869...",53|181|60|45|96|60|80|59|41|122|50|43|113|48|5...
319,05BAHQHA5RCI,9f279162e8d5c,1541633993,5,clickout item,NaN,DE,"Ulm, Germany",tablet,Best Value,"[2755290, 14054, 10243166, 3498770, 726906, 26...",59|86|70|58|86|58|58|57|78|68|55|90|79|64|112|...
340,062OG5L9831R,289b34a2bb4dd,1541663105,21,clickout item,NaN,TR,"Sigacik, Turkey",desktop,NaN,"[5828606, 6618430, 7828086, 8474478, 9225478, ...",45|44|51|40|28|50|43|28|26|46|30|27|55|110|44|...
354,06OT6WXN246O,ca92389e5ea65,1541688448,14,clickout item,NaN,KR,"Namhae, South Korea",desktop,NaN,"[4667086, 3152528, 5480450, 4341286, 5601476, ...",132|63|78|115|78|110|117|56|127|78|70|180|133|...
384,08GEUYKFOOPX,83ce8ea2a61b4,1541643155,30,clickout item,NaN,MY,"Malacca, Malaysia",mobile,NaN,"[3818266, 2547593, 3899110, 4599632, 377921, 5...",23|32|27|30|30|38|97|14|53|38|49|47|25|29|17|3...
447,091L4C793B1J,49816a95c986a,1541625659,63,clickout item,NaN,AR,"Bombinhas, Brazil",mobile,NaN,"[2504828, 2578276, 511676, 2344190, 1652507, 3...",135|76|62|93|51|45|75|28|40|76|32|27|50|77|92|...
449,09K0CO8F5AXJ,ccaf5005ee842,1541693719,2,clickout item,NaN,DE,"Leipzig, Germany",desktop,NaN,"[6605, 2270374, 12959, 6576, 1622837, 4122274,...",165|226|189|82|249|109|154|146|68|110|158|188|...
452,09X618WIVTP3,b1935d2a43d5e,1541688108,3,clickout item,NaN,MY,"Genting Highlands, Malaysia",mobile,NaN,"[1120687, 2165594, 5763948, 519501, 595286, 33...",39|76|78|55|87|38|47|143|57|53|21|8|78|17|59|1...
494,09YREZJA9YH3,572801ee070f0,1541688494,42,clickout item,NaN,TR,"Kozakli, Turkey",mobile,NaN,"[2032775, 491891, 1886115, 3877836, 5723470, 4...",27|24|50|37|27|53|56|40|40|18|40|42|25|24|21|4...
510,0A30V2M11MDK,dc8ded19d1781,1541689101,16,clickout item,NaN,NL,"Paris, France",desktop,Hotel Chain|Focus on Distance|Satisfactory Rating,"[362746, 48572, 48885, 49747, 48426, 50136, 85...",78|62|69|74|91|74|77|113|70|79|91|80|91|106|11...
512,0A8YWBYRBRTP,d29141ddbd43f,1541623589,2,clickout item,NaN,CA,"Ottawa, Canada",desktop,NaN,"[43495, 43652, 44038, 43503, 44682, 43765, 433...",109|106|106|119|89|141|103|93|89|93|81|106|126...
513,0BZN2KFMHLZF,d9497eeb946dc,1541668916,1,clickout item,NaN,BE,"Hasselt, Belgium",mobile,NaN,"[39730, 133101, 39758, 7029236, 455086, 388711...",90|88|80|80|90|62|65|90|89|75|70|109|165|104|6...
546,0CN5A7BJZRGW,0b105be325b12,1541657496,33,clickout item,NaN,IN,"Bengaluru, India",desktop,NaN,"[998041, 1389106, 1400686, 2216204, 2394112, 2...",11|47|23|19|12|8|16|16|23|16|18|19|15|22|103|2...
553,0D1M41K80XJ1,7567cae385981,1541660443,7,clickout item,NaN,HK,"Macau, China",desktop,NaN,"[2269838, 1439759, 211041, 1833415, 1331323, 9...",114|142|188|144|146|104|96|107|135|90|81|137|1...
554,0D1XFBRWUX7Z,35e873299a45f,1541586069,1,clickout item,NaN,AU,"Sydney, Australia",mobile,NaN,"[54865, 54803, 54953, 14211, 95510, 54838, 547...",163|126|158|177|145|85|107|158|132|189|187|131...
594,0DHC2FF92LFS,b4b881ddb91e0,1541601665,40,clickout item,NaN,AU,"Lorne, Australia",mobile,NaN,"[109119, 109118, 1018349, 2846590, 1885413, 29...",145|131|108|86|83|222|72|140|111|92|121|32|114...
597,0DJUQ92EQYM0,d2039eb924c5d,1541649689,3,clickout item,NaN,BR,"Águas Claras, Brazil",mobile,NaN,"[3145586, 5157920, 478986, 3993110, 478991, 57...",44|26|30|43|45|37|17|42|17|25|27|22|44|33|22|3...
598,0EPVF4QE049Q,11b583578f7f3,1541611766,1,clickout item,NaN,FI,"Seinäjoki, Finland",mobile,NaN,"[368306, 369426, 4916202, 2045589, 1328820, 36...",123|152|59|148|105|147|98|70|95|80|140
599,0GY71I4BUBQW,334177bbc6525,1541638087,1,clickout item,NaN,AU,"Rome, Italy",desktop,NaN,"[17112, 1374294, 17382, 2321776, 16895, 17056,...",81|95|126|79|186|112|53|112|56|214|142|77|71|1...
600,0H2RFN3FXM5A,e9fa318e4aad0,1541576918,1,clickout item,NaN,IN,"Bengaluru, India",mobile,NaN,"[1984531, 4775794, 1400686, 930783, 2612414, 1...",37|16|19|50|148|16|157|14|21|19|14|16|16|22|13...
602,0HG5FZNPFDYC,db55ce2d55626,1541571390,2,clickout item,NaN,RU,"Rostov-on-Don, Russia",mobile,NaN,"[10001880, 6452708, 7492016, 1048438, 10127018...",54|205|40|52|187|34|39|29|70|46|39|69|36|55|55...
...,...,...,...,...,...,...,...,...,...,...,...,...
3781666,Z6S5ELLKWH9U,b4cb947d63b06,1541642593,1,clickout item,NaN,NL,"Kralendijk, BES Islands",mobile,NaN,"[6893878, 30595, 5963500, 6931536, 975701, 305...",156|204|83|120|160|362|142|211|75|161|169|99|9...
3781668,Z6UH43QKBEFA,1a185e56b1687,1541592222,2,clickout item,NaN,AR,"Florianópolis, Brazil",desktop,NaN,"[5088964, 861491, 104832, 478996, 1330207, 186...",58|115|748|178|200|166|77|291|103|106|166|125|...
3781671,Z6UH5S6YCFGU,0de3309ea3315,1541625537,3,clickout item,NaN,US,"Las Vegas, USA",desktop,NaN,"[2793224, 8621, 1810141, 32727, 77124, 893925,...",182|278|764|182|139|108|273|174|106|111|244|14...
3781673,Z7H6WZBWLCXT,5d6cc2ee3db46,1541631030,2,clickout item,NaN,BR,"Fortaleza, Brazil",mobile,NaN,"[104802, 5032060, 104867, 104773, 104939, 1045...",71|99|98|89|139|70|90|103|115|86|113|89|48|53|...
3781687,Z8R3PNWG66WC,037d21739ccad,1541672836,14,clickout item,NaN,IT,"Amsterdam, Netherlands",mobile,NaN,"[1719593, 3152692, 4345706, 3154396, 42101, 14...",756|1177|254|986|962|724|169|534|690|310|359|2...
3781688,Z9GZ0O9E98XH,1694bed3ee9fb,1541667268,1,clickout item,NaN,AU,"Adelaide, Australia",desktop,NaN,"[667061, 101857, 995701, 14848, 3923476, 54864...",96|86|89|140|80|95|168|73|46|82|127|210|89|89|...
3781690,ZFD2YAQS3YX4,1e7237d9f35a8,1541709847,2,clickout item,NaN,BR,"São Paulo, Brazil",desktop,NaN,"[104912, 5816566, 478966, 104607, 104539, 1047...",138|365|144|136|183|79|84|457|96|216|104|129|1...
3781706,ZG9YRVARN8VE,7cc8c6b3f4a97,1541714873,16,clickout item,NaN,PE,"Máncora, Peru",mobile,NaN,"[3215419, 2828636, 3066968, 1796789, 2441706, ...",43|56|70|53|55|44|123|97|104|40|44|40|70|6|20|...
3781708,ZI483FNQTFE5,da06f0c5c4e27,1541664029,2,clickout item,NaN,IN,"Mumbai, India",mobile,NaN,"[4530384, 9757680, 9378320, 99502, 9661068, 96...",6|29|22|210|29|19|24|44|36|36|30|30|43|28|127|...
3781709,ZJDPHM5DWJCD,e1b43bf209d50,1541577899,1,clickout item,NaN,BE,"Grindelwald, Switzerland",mobile,NaN,"[15953, 1362025, 15233, 15955, 1008989, 730041...",134|148|212|239|64|105|126|564|126|564|709|218...
3781718,ZKABS031TSS3,82a1d6694e8fd,1541687528,9,clickout item,NaN,US,"Ivins, USA",mobile,NaN,"[387646, 10472726, 381376, 70720, 70701, 10828...",314|131|61|128|144|79|117|34|91|42|69|148|130|...
3781722,ZLZR6ZVNT61X,86632d06943ef,1541686280,4,clickout item,NaN,RU,"Çolakli, Turkey",mobile,NaN,"[94540, 13103, 96162, 863116, 97628, 1409690, ...",68|150|26|161|65|18|32|270|67|80|59|81|176|79|...
3781740,ZN0MI3V8DU6I,eec026e9dd8d9,1541560976,18,clickout item,NaN,US,"Vernon, USA",desktop,NaN,"[374956, 620556, 5964090, 2506754, 7846536, 39...",139|118|87|79|208|153|96|219|118
3781741,ZN7BDD39Y83X,929b6ba33334d,1541617907,1,clickout item,NaN,UK,"Glasgow, United Kingdom",mobile,NaN,"[152500, 18512, 627451, 1061780, 655466, 21778...",56|47|45|39|54|36|41|49|37|44|56|53|57|56|39|5...
3781755,ZOO280YM822I,d6a2d7a9d5711,1541554261,14,clickout item,NaN,TR,"Istanbul, Turkey",mobile,NaN,"[2773384, 5587842, 80224, 1346904, 80289, 8301...",33|41|33|31|35|35|42|40|32|26|39|36|42|33|21|3...
3781757,ZPII0N59F3R2,e341ad089f472,1541671799,2,clickout item,NaN,AU,"Reykjavík, Iceland",desktop,NaN,"[3757476, 102361, 6596362, 104092, 6299792, 20...",136|97|124|76|170|152|166|132|118|115|159|214|...
3781775,ZQDEMN3TBJ58,a60ba6624628a,1541639908,18,clickout item,NaN,BR,"Fortaleza, Brazil",desktop,NaN,"[104594, 104867, 104889, 1162971, 1201630, 104...",69|63|57|46|37|65|55|64|81|50|46|42|41|63|49|5...
3781776,ZT722F7KOKI8,66c459fc5f1d5,1541569655,1,clickout item,NaN,MX,"Chetumal, Mexico",mobile,NaN,"[2752786, 42775, 2777094, 2028173, 2637405, 31...",43|42|66|28|51|77|70|82|35|36|62|26|24|37|28|2...
3781780,ZU64EXB7HUSC,a12e64eb21788,1541618644,4,clickout item,NaN,US,"Victoria, Canada",desktop,NaN,"[44282, 44410, 44182, 837166, 1353966, 44243, ...",237|169|126|94|133|186|113|286|117|144|181|99|...
3781788,ZUCX42KNP5CA,911f86ae3cf64,1541678577,8,clickout item,NaN,JP,"Sasebo, Japan",desktop,Sort by Price,"[1738509, 1738515, 7689134, 2018845, 1179138, ...",54|100|108|116|135|154|192|208|216|217|249|269...
3781790,ZV68634ROL49,4f5808cfa765b,1541699124,2,clickout item,NaN,IN,"Mussoorie, India",mobile,NaN,"[2841397, 1005131, 2378072, 2378074, 2643434, ...",17|29|7|38|8|34|22|21|73|29|7|18|12|40|33|18|2...
3781839,ZVTSO44R1US2,ba077694ccf39,1541673409,49,clickout item,NaN,JP,"Sapporo, Japan",desktop,Hotel|Resort|Best Value|Hammam,"[5863172, 494271, 1042070, 103453, 9327438, 21...",72|90|100|92|81|86|92|83|81|100|105|104|95|87|...
3781840,ZVUSADAHBEMO,f5f4f9aa82b44,1541678661,1,clickout item,NaN,DE,"Grainau, Germany",desktop,NaN,"[51656, 96015, 52072, 5465, 5470, 5484, 117981...",146|200|124|99|88|133|112|85|79|95|87|95|95|91...
3781844,ZWB59UGA2UUY,6f5d6ebfe10b5,1541558109,4,clickout item,NaN,MY,"Kuala Lumpur, Malaysia",desktop,NaN,"[101409, 101389, 101381, 95870, 3484802, 10137...",38|47|44|52|48|48|40|41|32|60|106|46|56|56|103...
3781846,ZWD4F2A7H5EK,3e4fdd55f6145,1541670697,2,clickout item,NaN,IT,"Milan, Italy",desktop,NaN,"[20259, 20339, 20363, 20400, 20407, 954207, 20...",77|73|77|66|84|22|86|76|77|78|81|74|94|84|74|7...
3782317,ZXGCLNDBW84E,e73c90b6f448e,1541699269,466,clickout item,NaN,BR,"Porto Seguro, Brazil",desktop,NaN,"[916029, 1650015, 326846, 503361, 1326068, 477...",60|81|140|171|49|42|38|60|57|74|191|71|55|45|5...
3782325,ZYG4MMKT847V,0f128fd98b4e3,1541634384,4,clickout item,NaN,BR,"Resende, Brazil",mobile,NaN,"[1089752, 4103676, 2033145, 2684451, 2053814, ...",86|82|86|40|92|56|83|54|145|114|58|67|40|87|46...
3782327,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,clickout item,NaN,US,"Holiday City, USA",mobile,NaN,"[364796, 1299248, 4891790, 381296, 1345175, 96...",92|52|92|89|59|275
3782333,ZZ39YE45SZIE,f5db4092ec9fc,1541551945,6,clickout item,NaN,HK,"Taitung City, Taiwan",mobile,NaN,"[9925140, 2625125, 5779140, 7365168, 5849342, ...",219|215|183|215|590|70|131|111|64|65|127|94|64...
3782334,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,"[46149, 109974, 46119, 8333280, 12455, 1185556...",138|138|156|153|128|202|145|137|105|68|133|167...

In [12]:
# Per ciascun clickout da predire, si ordinano le impressions in base alla popolarità per quella città

#from itertools import islice

for index,row in df_target_copy.iterrows():
    if(df_city_occurrencies[df_city_occurrencies['city'] == row['city']].shape[0] > 0):
        occ = df_city_occurrencies[df_city_occurrencies['city'] == row['city']]['occurrencies'].values[0]
        new_ord = {}
        impr = row['impressions']
        for i in impr:
            if i in occ:
                new_ord[i] = occ.get(i)
        new_ord = Counter(new_ord)
        #[key for key, _ in counter.most_common()] #convert the counter object to list with only references
        df_target_copy.at[index, 'impressions'] = [key for key, _ in new_ord.most_common()]

KeyboardInterrupt:

In [ ]:
for index, row in df_target_copy.iterrows():
    df_target_copy.at[index, 'impressions'] =  " ".join(str(x) for x in row['impressions'])

In [38]:
df_t = df_target_copy[['user_id','session_id','timestamp','step','impressions']]
df_t

,user_id,session_id,timestamp,step,impressions
6,004A07DM0IDW,1d688ec168932,1541555799,7,"[399441, 127128, 2033381, 1167004, 1724779, 12..."
8,009RGHI3G9A3,f05ab0de907e2,1541570940,2,"[10884872, 7065316]"
10,00Y1Z24X8084,26b6d294d66e7,1541651823,2,"[4476010, 9343000, 7101352, 3843244, 5101686, ..."
15,01V3WDTDM5CU,07628a0f5be0b,1541575643,5,"[2817590, 2012359, 3180004, 6434434, 4115018, ..."
61,02AOAVF9PVYH,4a01c3afbc224,1541681278,46,"[1393443, 559091, 1177548, 559056, 1451247, 10..."
109,0339C84S24ET,89171d441a304,1541615683,36,"[5647680, 9500346, 8276346, 4500498, 5055970, ..."
111,0386OH8JDE1Q,e09591d07cdef,1541620536,2,"[1193320, 5488246, 3858774]"
115,03LTH89QY623,7663406cf586c,1541554183,4,"[1638525, 59566, 75269, 77258, 906477, 1017869..."
138,03VT0ODUTZB0,725e8adf70e86,1541632490,23,"[109938, 164193, 322491, 1070666, 492516, 1642..."
314,03XH0JWCWHAM,73f4c417ff730,1541566143,176,"[42692, 349091, 42876, 5702804, 6953534, 10129..."
319,05BAHQHA5RCI,9f279162e8d5c,1541633993,5,"[2616752, 8954902, 2071844, 726906, 25860, 140..."
340,062OG5L9831R,289b34a2bb4dd,1541663105,21,"[5828606, 6618430, 8176004, 7828086, 8474478, ..."
354,06OT6WXN246O,ca92389e5ea65,1541688448,14,"[4667086, 3152528, 5601476, 5480450, 5892026, ..."
384,08GEUYKFOOPX,83ce8ea2a61b4,1541643155,30,"[3818266, 2547593, 508851, 3816128, 684641, 37..."
447,091L4C793B1J,49816a95c986a,1541625659,63,"[2578276, 7219768, 2382352, 2344190, 3873584, ..."
449,09K0CO8F5AXJ,ccaf5005ee842,1541693719,2,"[1622837, 12959, 6605, 14471, 2270374, 4122274..."
452,09X618WIVTP3,b1935d2a43d5e,1541688108,3,"[2165594, 5763948, 3386520, 1120687, 595286, 4..."
494,09YREZJA9YH3,572801ee070f0,1541688494,42,"[8755832, 2032775, 4493250, 5723470, 9027460, ..."
510,0A30V2M11MDK,dc8ded19d1781,1541689101,16,"[48661, 50136, 49218, 49244, 48747, 48883, 485..."
512,0A8YWBYRBRTP,d29141ddbd43f,1541623589,2,"[44038, 43652, 43765, 44228, 44682, 43503, 434..."
513,0BZN2KFMHLZF,d9497eeb946dc,1541668916,1,"[39758, 133101, 39730, 107902, 3887112, 702923..."
546,0CN5A7BJZRGW,0b105be325b12,1541657496,33,"[5684276, 2817576, 4775794, 2216204, 1400686, ..."
553,0D1M41K80XJ1,7567cae385981,1541660443,7,"[2269838, 211041, 4374008, 54152, 923995, 1833..."
554,0D1XFBRWUX7Z,35e873299a45f,1541586069,1,"[54803, 54953, 14211, 54982, 55093, 54794, 955..."
594,0DHC2FF92LFS,b4b881ddb91e0,1541601665,40,"[109119, 109118, 105237, 1018349, 1885413, 214..."
597,0DJUQ92EQYM0,d2039eb924c5d,1541649689,3,"[3145586, 5157920, 478991, 4842146, 478986, 39..."
598,0EPVF4QE049Q,11b583578f7f3,1541611766,1,"[368306, 369426, 4916202, 2045589, 1328820, 36..."
599,0GY71I4BUBQW,334177bbc6525,1541638087,1,"[17056, 17108, 848536, 3194342, 2200778, 17608..."
600,0H2RFN3FXM5A,e9fa318e4aad0,1541576918,1,"[5684276, 4775794, 1400686, 7204042, 3969446, ..."
602,0HG5FZNPFDYC,db55ce2d55626,1541571390,2,"[1165724, 4726076, 1048438, 1370240, 3193776, ..."
...,...,...,...,...,...
3781666,Z6S5ELLKWH9U,b4cb947d63b06,1541642593,1,"[6893878, 30595, 5963500, 6931536, 975701, 305..."
3781668,Z6UH43QKBEFA,1a185e56b1687,1541592222,2,"[5088964, 861491, 104832, 478996, 1330207, 186..."
3781671,Z6UH5S6YCFGU,0de3309ea3315,1541625537,3,"[2793224, 8621, 1810141, 32727, 77124, 893925,..."
3781673,Z7H6WZBWLCXT,5d6cc2ee3db46,1541631030,2,"[104802, 5032060, 104867, 104773, 104939, 1045..."
3781687,Z8R3PNWG66WC,037d21739ccad,1541672836,14,"[1719593, 3152692, 4345706, 3154396, 42101, 14..."
3781688,Z9GZ0O9E98XH,1694bed3ee9fb,1541667268,1,"[667061, 101857, 995701, 14848, 3923476, 54864..."
3781690,ZFD2YAQS3YX4,1e7237d9f35a8,1541709847,2,"[104912, 5816566, 478966, 104607, 104539, 1047..."
3781706,ZG9YRVARN8VE,7cc8c6b3f4a97,1541714873,16,"[3215419, 2828636, 3066968, 1796789, 2441706, ..."
3781708,ZI483FNQTFE5,da06f0c5c4e27,1541664029,2,"[4530384, 9757680, 9378320, 99502, 9661068, 96..."
3781709,ZJDPHM5DWJCD,e1b43bf209d50,1541577899,1,"[15953, 1362025, 15233, 15955, 1008989, 730041..."
3781718,ZKABS031TSS3,82a1d6694e8fd,1541687528,9,"[387646, 10472726, 381376, 70720, 70701, 10828..."
3781722,ZLZR6ZVNT61X,86632d06943ef,1541686280,4,"[94540, 13103, 96162, 863116, 97628, 1409690, ..."
3781740,ZN0MI3V8DU6I,eec026e9dd8d9,1541560976,18,"[374956, 620556, 5964090, 2506754, 7846536, 39..."
3781741,ZN7BDD39Y83X,929b6ba33334d,1541617907,1,"[152500, 18512, 627451, 1061780, 655466, 21778..."
3781755,ZOO280YM822I,d6a2d7a9d5711,1541554261,14,"[2773384, 5587842, 80224, 1346904, 80289, 8301..."
3781757,ZPII0N59F3R2,e341ad089f472,1541671799,2,"[3757476, 102361, 6596362, 104092, 6299792, 20..."
3781775,ZQDEMN3TBJ58,a60ba6624628a,1541639908,18,"[104594, 104867, 104889, 1162971, 1201630, 104..."
3781776,ZT722F7KOKI8,66c459fc5f1d5,1541569655,1,"[2752786, 42775, 2777094, 2028173, 2637405, 31..."
3781780,ZU64EXB7HUSC,a12e64eb21788,1541618644,4,"[44282, 44410, 44182, 837166, 1353966, 44243, ..."
3781788,ZUCX42KNP5CA,911f86ae3cf64,1541678577,8,"[1738509, 1738515, 7689134, 2018845, 1179138, ..."
3781790,ZV68634ROL49,4f5808cfa765b,1541699124,2,"[2841397, 1005131, 2378072, 2378074, 2643434, ..."
3781839,ZVTSO44R1US2,ba077694ccf39,1541673409,49,"[5863172, 494271, 1042070, 103453, 9327438, 21..."
3781840,ZVUSADAHBEMO,f5f4f9aa82b44,1541678661,1,"[51656, 96015, 52072, 5465, 5470, 5484, 117981..."
3781844,ZWB59UGA2UUY,6f5d6ebfe10b5,1541558109,4,"[101409, 101389, 101381, 95870, 3484802, 10137..."
3781846,ZWD4F2A7H5EK,3e4fdd55f6145,1541670697,2,"[20259, 20339, 20363, 20400, 20407, 954207, 20..."
3782317,ZXGCLNDBW84E,e73c90b6f448e,1541699269,466,"[916029, 1650015, 326846, 503361, 1326068, 477..."
3782325,ZYG4MMKT847V,0f128fd98b4e3,1541634384,4,"[1089752, 4103676, 2033145, 2684451, 2053814, ..."
3782327,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,"[364796, 1299248, 4891790, 381296, 1345175, 96..."
3782333,ZZ39YE45SZIE,f5db4092ec9fc,1541551945,6,"[9925140, 2625125, 5779140, 7365168, 5849342, ..."
3782334,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,"[46149, 109974, 46119, 8333280, 12455, 1185556..."

In [ ]:
df_sub = df_t.copy()
df_sub.columns = ['user_id','session_id','timestamp','step','item_recommendations']

In [84]:
#df_sub.to_csv("../location_subm.csv", encoding='utf-8', index=False)

In [9]:
# Seconda submission considerando solo i clickout delle sessioni che non hanno riferimento numerico 
# nella sessione. Per il resto dei clickout è mantenuto l'ordine di apparizione nelle impressions
# Score: 0.41463  
def existsIndex(df, idx):
    try:
        df.loc[idx]
        return True
    except KeyError:
        return False
def func(x):
    y = x[x['reference'].isnull()]
    if len(y) == 1:
        return x
    
def RepresentsInt(s):
    try: 
        int(s)
        return True
    except ValueError:
        return False

In [10]:
just_missing_refs = df_test[df_test['reference'].isnull()]
just_missing_refs = just_missing_refs[just_missing_refs['action_type'] == 'clickout item']

In [11]:
just_missing_refs

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
6,004A07DM0IDW,1d688ec168932,1541555799,7,clickout item,NaN,CO,"Santa Marta, Colombia",mobile,NaN,2059240|2033381|1724779|127131|399441|103357|1...,70|46|48|76|65|65|106|66|87|43|52|44|60|61|50|...
8,009RGHI3G9A3,f05ab0de907e2,1541570940,2,clickout item,NaN,IN,"Nathdwara, India",mobile,NaN,10884872|7065316,64|28
10,00Y1Z24X8084,26b6d294d66e7,1541651823,2,clickout item,NaN,PH,"Iloilo City, Philippines",mobile,NaN,2714480|4476010|3843244|3833012|9017890|198100...,74|14|22|38|55|44|28|34|23|27|12|108|19|21|36|...
15,01V3WDTDM5CU,07628a0f5be0b,1541575643,5,clickout item,NaN,PL,"Wisla, Poland",mobile,Sort by Price,3565720|2947584|4115018|2039671|3836538|801409...,16|18|20|21|22|22|28|28|28|30|30|33|33|35|35|3...
61,02AOAVF9PVYH,4a01c3afbc224,1541681278,46,clickout item,NaN,JP,"Yokohama, Japan",desktop,Hotel|Resort|Sort by Price,1451247|559056|1045096|1963879|693596|1967173|...,80|81|81|82|82|82|83|83|83|85|85|88|88|91|92|9...
109,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,13361|5647680|116764|898719|8276346|9168|19325...,185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...
111,0386OH8JDE1Q,e09591d07cdef,1541620536,2,clickout item,NaN,UK,"John o' Groats, United Kingdom",desktop,NaN,1193320|5488246|3858774|4552034|10620372|22696...,103|88|100|134|109|138|126|86
115,03LTH89QY623,7663406cf586c,1541554183,4,clickout item,NaN,CA,"Koloa, USA",desktop,NaN,241961|906477|991561|353701|1149665|77258|4943...,287|300|261|197|163|263|262|188|540|283|211|22...
138,03VT0ODUTZB0,725e8adf70e86,1541632490,23,clickout item,NaN,UK,"Warrington, United Kingdom",desktop,NaN,109938|164193|632366|1362450|1070666|164220|11...,45|67|78|60|58|57|86|68|57|55|148|92|66|55|61|...
314,03XH0JWCWHAM,73f4c417ff730,1541566143,176,clickout item,NaN,MX,"Puebla, Mexico",mobile,Sort By Popularity,42692|5116230|42876|4342578|42864|3148690|2123...,53|181|60|45|96|60|80|59|41|122|50|43|113|48|5...
319,05BAHQHA5RCI,9f279162e8d5c,1541633993,5,clickout item,NaN,DE,"Ulm, Germany",tablet,Best Value,2755290|14054|10243166|3498770|726906|2616752|...,59|86|70|58|86|58|58|57|78|68|55|90|79|64|112|...
340,062OG5L9831R,289b34a2bb4dd,1541663105,21,clickout item,NaN,TR,"Sigacik, Turkey",desktop,NaN,5828606|6618430|7828086|8474478|9225478|991468...,45|44|51|40|28|50|43|28|26|46|30|27|55|110|44|...
354,06OT6WXN246O,ca92389e5ea65,1541688448,14,clickout item,NaN,KR,"Namhae, South Korea",desktop,NaN,4667086|3152528|5480450|4341286|5601476|397494...,132|63|78|115|78|110|117|56|127|78|70|180|133|...
384,08GEUYKFOOPX,83ce8ea2a61b4,1541643155,30,clickout item,NaN,MY,"Malacca, Malaysia",mobile,NaN,3818266|2547593|3899110|4599632|377921|508851|...,23|32|27|30|30|38|97|14|53|38|49|47|25|29|17|3...
447,091L4C793B1J,49816a95c986a,1541625659,63,clickout item,NaN,AR,"Bombinhas, Brazil",mobile,NaN,2504828|2578276|511676|2344190|1652507|3242334...,135|76|62|93|51|45|75|28|40|76|32|27|50|77|92|...
449,09K0CO8F5AXJ,ccaf5005ee842,1541693719,2,clickout item,NaN,DE,"Leipzig, Germany",desktop,NaN,6605|2270374|12959|6576|1622837|4122274|195595...,165|226|189|82|249|109|154|146|68|110|158|188|...
452,09X618WIVTP3,b1935d2a43d5e,1541688108,3,clickout item,NaN,MY,"Genting Highlands, Malaysia",mobile,NaN,1120687|2165594|5763948|519501|595286|3386520|...,39|76|78|55|87|38|47|143|57|53|21|8|78|17|59|1...
494,09YREZJA9YH3,572801ee070f0,1541688494,42,clickout item,NaN,TR,"Kozakli, Turkey",mobile,NaN,2032775|491891|1886115|3877836|5723470|4493250...,27|24|50|37|27|53|56|40|40|18|40|42|25|24|21|4...
510,0A30V2M11MDK,dc8ded19d1781,1541689101,16,clickout item,NaN,NL,"Paris, France",desktop,Hotel Chain|Focus on Distance|Satisfactory Rating,362746|48572|48885|49747|48426|50136|85862|496...,78|62|69|74|91|74|77|113|70|79|91|80|91|106|11...
512,0A8YWBYRBRTP,d29141ddbd43f,1541623589,2,clickout item,NaN,CA,"Ottawa, Canada",desktop,NaN,43495|43652|44038|43503|44682|43765|43359|4361...,109|106|106|119|89|141|103|93|89|93|81|106|126...
513,0BZN2KFMHLZF,d9497eeb946dc,1541668916,1,clickout item,NaN,BE,"Hasselt, Belgium",mobile,NaN,39730|133101|39758|7029236|455086|3887112|1070...,90|88|80|80|90|62|65|90|89|75|70|109|165|104|6...
546,0CN5A7BJZRGW,0b105be325b12,1541657496,33,clickout item,NaN,IN,"Bengaluru, India",desktop,NaN,998041|1389106|1400686|2216204|2394112|2817576...,11|47|23|19|12|8|16|16|23|16|18|19|15|22|103|2...
553,0D1M41K80XJ1,7567cae385981,1541660443,7,clickout item,NaN,HK,"Macau, China",desktop,NaN,2269838|1439759|211041|1833415|1331323|923995|...,114|142|188|144|146|104|96|107|135|90|81|137|1...
554,0D1XFBRWUX7Z,35e873299a45f,1541586069,1,clickout item,NaN,AU,"Sydney, Australia",mobile,NaN,54865|54803|54953|14211|95510|54838|54794|1484...,163|126|158|177|145|85|107|158|132|189|187|131...
594,0DHC2FF92LFS,b4b881ddb91e0,1541601665,40,clickout item,NaN,AU,"Lorne, Australia",mobile,NaN,109119|109118|1018349|2846590|1885413|2941498|...,145|131|108|86|83|222|72|140|111|92|121|32|114...
597,0DJUQ92EQYM0,d2039eb924c5d,1541649689,3,clickout item,NaN,BR,"Águas Claras, Brazil",mobile,NaN,3145586|5157920|478986|3993110|478991|5790206|...,44|26|30|43|45|37|17|42|17|25|27|22|44|33|22|3...
598,0EPVF4QE049Q,11b583578f7f3,1541611766,1,clickout item,NaN,FI,"Seinäjoki, Finland",mobile,NaN,368306|369426|4916202|2045589|1328820|369421|1...,123|152|59|148|105|147|98|70|95|80|140
599,0GY71I4BUBQW,334177bbc6525,1541638087,1,clickout item,NaN,AU,"Rome, Italy",desktop,NaN,17112|1374294|17382|2321776|16895|17056|17108|...,81|95|126|79|186|112|53|112|56|214|142|77|71|1...
600,0H2RFN3FXM5A,e9fa318e4aad0,1541576918,1,clickout item,NaN,IN,"Bengaluru, India",mobile,NaN,1984531|4775794|1400686|930783|2612414|1199716...,37|16|19|50|148|16|157|14|21|19|14|16|16|22|13...
602,0HG5FZNPFDYC,db55ce2d55626,1541571390,2,clickout item,NaN,RU,"Rostov-on-Don, Russia",mobile,NaN,10001880|6452708|7492016|1048438|10127018|4726...,54|205|40|52|187|34|39|29|70|46|39|69|36|55|55...
...,...,...,...,...,...,...,...,...,...,...,...,...
3781666,Z6S5ELLKWH9U,b4cb947d63b06,1541642593,1,clickout item,NaN,NL,"Kralendijk, BES Islands",mobile,NaN,6893878|30595|5963500|6931536|975701|30599|877...,156|204|83|120|160|362|142|211|75|161|169|99|9...
3781668,Z6UH43QKBEFA,1a185e56b1687,1541592222,2,clickout item,NaN,AR,"Florianópolis, Brazil",desktop,NaN,5088964|861491|104832|478996|1330207|1862179|2...,58|115|748|178|200|166|77|291|103|106|166|125|...
3781671,Z6UH5S6YCFGU,0de3309ea3315,1541625537,3,clickout item,NaN,US,"Las Vegas, USA",desktop,NaN,2793224|8621|1810141|32727|77124|893925|8518|2...,182|278|764|182|139|108|273|174|106|111|244|14...
3781673,Z7H6WZBWLCXT,5d6cc2ee3db46,1541631030,2,clickout item,NaN,BR,"Fortaleza, Brazil",mobile,NaN,104802|5032060|104867|104773|104939|104505|104...,71|99|98|89|139|70|90|103|115|86|113|89|48|53|...
3781687,Z8R3PNWG66WC,037d21739ccad,1541672836,14,clickout item,NaN,IT,"Amsterdam, Netherlands",mobile,NaN,1719593|3152692|4345706|3154396|42101|147253|1...,756|1177|254|986|962|724|169|534|690|310|359|2...
3781688,Z9GZ0O9E98XH,1694bed3ee9fb,1541667268,1,clickout item,NaN,AU,"Adelaide, Australia",desktop,NaN,667061|101857|995701|14848|3923476|54864|10923...,96|86|89|140|80|95|168|73|46|82|127|210|89|89|...
3781690,ZFD2YAQS3YX4,1e7237d9f35a8,1541709847,2,clickout item,NaN,BR,"São Paulo, Brazil",desktop,NaN,104912|5816566|478966|104607|104539|104710|597...,138|365|144|136|183|79|84|457|96|216|104|129|1...
3781706,ZG9YRVARN8VE,7cc8c6b3f4a97,1541714873,16,clickout item,NaN,PE,"Máncora, Peru",mobile,NaN,3215419|2828636|3066968|1796789|2441706|271802...,43|56|70|53|55|44|123|97|104|40|44|40|70|6|20|...
3781708,ZI483FNQTFE5,da06f0c5c4e27,1541664029,2,clickout item,NaN,IN,"Mumbai, India",mobile,NaN,4530384|9757680|9378320|99502|9661068|9618174|...,6|29|22|210|29|19|24|44|36|36|30|30|43|28|127|...
3781709,ZJDPHM5DWJCD,e1b43bf209d50,1541577899,1,clickout item,NaN,BE,"Grindelwald, Switzerland",mobile,NaN,15953|1362025|15233|15955|1008989|7300410|1410...,134|148|212|239|64|105|126|564|126|564|709|218...
3781718,ZKABS031TSS3,82a1d6694e8fd,1541687528,9,clickout item,NaN,US,"Ivins, USA",mobile,NaN,387646|10472726|381376|70720|70701|1082856|677...,314|131|61|128|144|79|117|34|91|42|69|148|130|...
3781722,ZLZR6ZVNT61X,86632d06943ef,1541686280,4,clickout item,NaN,RU,"Çolakli, Turkey",mobile,NaN,94540|13103|96162|863116|97628|1409690|486686|...,68|150|26|161|65|18|32|270|67|80|59|81|176|79|...
3781740,ZN0MI3V8DU6I,eec026e9dd8d9,1541560976,18,clickout item,NaN,US,"Vernon, USA",desktop,NaN,374956|620556|5964090|2506754|7846536|393276|2...,139|118|87|79|208|153|96|219|118
3781741,ZN7BDD39Y83X,929b6ba33334d,1541617907,1,clickout item,NaN,UK,"Glasgow, United Kingdom",mobile,NaN,152500|18512|627451|1061780|655466|2177802|123...,56|47|45|39|54|36|41|49|37|44|56|53|57|56|39|5...
3781755,ZOO280YM822I,d6a2d7a9d5711,1541554261,14,clickout item,NaN,TR,"Istanbul, Turkey",mobile,NaN,2773384|5587842|80224|1346904|80289|8301508|40...,33|41|33|31|35|35|42|40|32|26|39|36|42|33|21|3...
3781757,ZPII0N59F3R2,e341ad089f472,1541671799,2,clickout item,NaN,AU,"Reykjavík, Iceland",desktop,NaN,3757476|102361|6596362|104092|6299792|2081670|...,136|97|124|76|170|152|166|132|118|115|159|214|...
3781775,ZQDEMN3TBJ58,a60ba6624628a,1541639908,18,clickout item,NaN,BR,"Fortaleza, Brazil",desktop,NaN,104594|104867|104889|1162971|1201630|104888|10...,69|63|57|46|37|65|55|64|81|50|46|42|41|63|49|5...
3781776,ZT722F7KOKI8,66c459fc5f1d5,1541569655,1,clickout item,NaN,MX,"Chetumal, Mexico",mobile,NaN,2752786|42775|2777094|2028173|2637405|3140790|...,43|42|66|28|51|77|70|82|35|36|62|26|24|37|28|2...
3781780,ZU64EXB7HUSC,a12e64eb21788,1541618644,4,clickout item,NaN,US,"Victoria, Canada",desktop,NaN,44282|44410|44182|837166|1353966|44243|44679|4...,237|169|126|94|133|186|113|286|117|144|181|99|...
3781788,ZUCX42KNP5CA,911f86ae3cf64,1541678577,8,clickout item,NaN,JP,"Sasebo, Japan",desktop,Sort by Price,1738509|1738515|7689134|2018845|1179138|106494...,54|100|108|116|135|154|192|208|216|217|249|269...
3781790,ZV68634ROL49,4f5808cfa765b,1541699124,2,clickout item,NaN,IN,"Mussoorie, India",mobile,NaN,2841397|1005131|2378072|2378074|2643434|312778...,17|29|7|38|8|34|22|21|73|29|7|18|12|40|33|18|2...
3781839,ZVTSO44R1US2,ba077694ccf39,1541673409,49,clickout item,NaN,JP,"Sapporo, Japan",desktop,Hotel|Resort|Best Value|Hammam,5863172|494271|1042070|103453|9327438|2111024|...,72|90|100|92|81|86|92|83|81|100|105|104|95|87|...
3781840,ZVUSADAHBEMO,f5f4f9aa82b44,1541678661,1,clickout item,NaN,DE,"Grainau, Germany",desktop,NaN,51656|96015|52072|5465|5470|5484|117981|255274...,146|200|124|99|88|133|112|85|79|95|87|95|95|91...
3781844,ZWB59UGA2UUY,6f5d6ebfe10b5,1541558109,4,clickout item,NaN,MY,"Kuala Lumpur, Malaysia",desktop,NaN,101409|101389|101381|95870|3484802|101373|1945...,38|47|44|52|48|48|40|41|32|60|106|46|56|56|103...
3781846,ZWD4F2A7H5EK,3e4fdd55f6145,1541670697,2,clickout item,NaN,IT,"Milan, Italy",desktop,NaN,20259|20339|20363|20400|20407|954207|20564|202...,77|73|77|66|84|22|86|76|77|78|81|74|94|84|74|7...
3782317,ZXGCLNDBW84E,e73c90b6f448e,1541699269,466,clickout item,NaN,BR,"Porto Seguro, Brazil",desktop,NaN,916029|1650015|326846|503361|1326068|477936|38...,60|81|140|171|49|42|38|60|57|74|191|71|55|45|5...
3782325,ZYG4MMKT847V,0f128fd98b4e3,1541634384,4,clickout item,NaN,BR,"Resende, Brazil",mobile,NaN,1089752|4103676|2033145|2684451|2053814|279089...,86|82|86|40|92|56|83|54|145|114|58|67|40|87|46...
3782327,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,clickout item,NaN,US,"Holiday City, USA",mobile,NaN,364796|1299248|4891790|381296|1345175|9647370,92|52|92|89|59|275
3782333,ZZ39YE45SZIE,f5db4092ec9fc,1541551945,6,clickout item,NaN,HK,"Taitung City, Taiwan",mobile,NaN,9925140|2625125|5779140|7365168|5849342|198775...,219|215|183|215|590|70|131|111|64|65|127|94|64...
3782334,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,46149|109974|46119|8333280|12455|1185556|84002...,138|138|156|153|128|202|145|137|105|68|133|167...

In [16]:
count_last_ref_numeric = []
count_last_ref_not_numeric_numeric_before = []
count_no_ref_numeric_in_session = []
for idx, row in just_missing_refs.iterrows():
    sess = row['session_id']
    i = 1
    while True:
        if not existsIndex(df, idx - i):
            count_no_ref_numeric_in_session.append(sess)
            break
        prev_row = df.loc[idx - i]
        if prev_row['session_id'] != sess:
            count_no_ref_numeric_in_session.append(sess)
            break
        if RepresentsInt(prev_row['reference']):
            if i == 1:
                count_last_ref_numeric.append(sess)
                break
            else:
                count_last_ref_not_numeric_numeric_before.append(sess)
                break
        else:
            i += 1

In [17]:
len(count_no_ref_numeric_in_session)

88961

In [43]:
df_t = df_test.copy()

In [44]:
df_no_ref = df_t[df_t['session_id'].isin(count_no_ref_numeric_in_session)]
mask = df_no_ref["reference"].isnull() & (df_no_ref["action_type"] == "clickout item")
df_no_ref = df_no_ref[mask]
df_no_ref.loc[:,'impressions'] = df_no_ref['impressions'].apply(string_to_array)

In [21]:
from tqdm import tqdm_notebook as tqdm

In [23]:
for index,row in tqdm(df_no_ref.iterrows()):
    if(df_city_occurrencies[df_city_occurrencies['city'] == row['city']].shape[0] > 0):
        occ = df_city_occurrencies[df_city_occurrencies['city'] == row['city']]['occurrencies'].values[0]
        new_ord = {}
        impr = row['impressions']
        for i in impr:
            if i in occ:
                new_ord[i] = occ.get(i)
        new_ord = Counter(new_ord)
        df_no_ref.at[index, 'impressions'] = [key for key, _ in new_ord.most_common()]
    
df_no_ref

HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
319,05BAHQHA5RCI,9f279162e8d5c,1541633993,5,clickout item,NaN,DE,"Ulm, Germany",tablet,Best Value,"[2616752, 8954902, 2071844, 726906, 25860, 140...",59|86|70|58|86|58|58|57|78|68|55|90|79|64|112|...
513,0BZN2KFMHLZF,d9497eeb946dc,1541668916,1,clickout item,NaN,BE,"Hasselt, Belgium",mobile,NaN,"[39758, 133101, 39730, 107902, 3887112, 702923...",90|88|80|80|90|62|65|90|89|75|70|109|165|104|6...
554,0D1XFBRWUX7Z,35e873299a45f,1541586069,1,clickout item,NaN,AU,"Sydney, Australia",mobile,NaN,"[54803, 54953, 14211, 54982, 55093, 54794, 955...",163|126|158|177|145|85|107|158|132|189|187|131...
598,0EPVF4QE049Q,11b583578f7f3,1541611766,1,clickout item,NaN,FI,"Seinäjoki, Finland",mobile,NaN,"[368306, 369426, 4916202, 2045589, 1328820, 36...",123|152|59|148|105|147|98|70|95|80|140
599,0GY71I4BUBQW,334177bbc6525,1541638087,1,clickout item,NaN,AU,"Rome, Italy",desktop,NaN,"[17056, 17108, 848536, 3194342, 2200778, 17608...",81|95|126|79|186|112|53|112|56|214|142|77|71|1...
600,0H2RFN3FXM5A,e9fa318e4aad0,1541576918,1,clickout item,NaN,IN,"Bengaluru, India",mobile,NaN,"[5684276, 4775794, 1400686, 7204042, 3969446, ...",37|16|19|50|148|16|157|14|21|19|14|16|16|22|13...
602,0HG5FZNPFDYC,db55ce2d55626,1541571390,2,clickout item,NaN,RU,"Rostov-on-Don, Russia",mobile,NaN,"[1165724, 4726076, 1048438, 1370240, 3193776, ...",54|205|40|52|187|34|39|29|70|46|39|69|36|55|55...
604,0HPR8MG837GZ,9e3e3ac5954f3,1541648887,2,clickout item,NaN,BR,"Boston, USA",tablet,NaN,"[8504, 8500, 3248570, 79307, 67917, 73974, 849...",100|72|117|63|125|106|210|77|76|99|99|113|113|...
682,0L2CALL26C66,59bfbcb10146d,1541593658,1,clickout item,NaN,PL,"Alicante, Spain",desktop,NaN,"[40109, 6724, 6721, 147227, 32937, 80983, 1194...",30|36|42|88|46|85|49|57|45|49|56|53|37|63|127|...
801,0ME9OE1GS1Q9,7afb20460a368,1541591150,1,clickout item,NaN,BG,"Prague, Czech Republic",mobile,NaN,"[14243, 13699, 100667, 1487955, 80400, 80376, ...",61|45|62|32|42|57|54|135|58|79|85|49|69|129|10...
813,0NK2TU8JS5IE,c0e1d70377e8d,1541586959,2,clickout item,NaN,AU,"Weipa, Australia",mobile,NaN,"[2188426, 3092731]",98|117
815,0NMWJUR0YYSU,e3e39b4041170,1541677811,2,clickout item,NaN,DE,"Frankenberg, Germany",mobile,NaN,"[5166404, 406646, 1119240]",199|94|69|164|158|121|118|80|110|82|85|74|62|5...
1060,0Q3W4X8HG57M,51c88e49fb6dc,1541612840,1,clickout item,NaN,FR,"Hong Kong, Hong Kong",mobile,NaN,"[54132, 8905500, 1204728, 132653, 16543, 22779...",281|367|313|225|210|398|442|255|381|340|380|30...
1062,0Q4LCRC7V5H5,2699fea9e59a3,1541663905,2,clickout item,NaN,MY,"Port Dickson, Malaysia",desktop,NaN,"[693816, 2621838, 8131766, 2878935, 3864648, 4...",43|48|17|38|23|30|45|18|26|31|36|40|33|31|29|2...
1125,0S6ZR5UCAHUK,88fe3fde210f4,1541650657,1,clickout item,NaN,RO,"Sibiu, Romania",desktop,NaN,"[7902572, 400791, 6919316, 1314825, 972027, 13...",37|22|80|42|103|50|78|69|19|33|36|28|92|41|22|...
1130,0SCD8YVIKSN2,24d7d52ceab06,1541673353,5,clickout item,NaN,DE,"Dülmen, Germany",mobile,Sort By Popularity,"[246536, 418191]",90|86|80|190|79|95|86|85|106|131|120|98|88|86|...
1138,0T44QW6172IY,fa85ee327cffd,1541695828,8,clickout item,NaN,US,"Philadelphia, USA",mobile,Sort by Price,"[71935, 72588, 60580, 65022, 63341, 64784, 712...",74|75|78|79|83|87|90|92|96|96|104|108|109|111|...
1139,0UCBRUGP6YHU,f57abecfdc90e,1541704893,1,clickout item,NaN,DE,"Antwerp, Belgium",desktop,NaN,"[1583829, 8735372, 54640, 1311324, 14856, 5462...",109|154|54|59|98|109|170|131|127|60|134|135|66...
1179,0XJ0Z6P56N9I,b41da7780da40,1541620930,1,clickout item,NaN,BR,"São Mateus, Brazil",mobile,NaN,"[5822472, 1496457, 2814052, 8285932, 8210882, ...",65|30|18|32|21|42|37|53|53|36|28|35|29|29|25|3...
1214,0ZDT54YLI2CZ,6d47d9ced40b8,1541697469,1,clickout item,NaN,AA,"Tunis, Tunisia",mobile,NaN,"[476726, 80313, 134204, 1207351, 80337, 631940...",172|233|46|110|86|110|36|89|138|80|84|73|155|4...
1215,11M984G1M7XV,64933b468cfdb,1541604041,1,clickout item,NaN,JP,"Tokyo, Japan",mobile,NaN,"[103600, 3132670, 5452024, 3143733, 818501, 95...",146|169|302|122|308|71|136|79|263|77|113|162|7...
1216,125O1BL39BD9,b576195b2922a,1541577830,1,clickout item,NaN,NL,"Rotterdam, Netherlands",mobile,NaN,"[33056, 2836261, 42154, 33055, 33139, 8191264,...",107|102|131|181|61|170|128|155|84|124|93|123|9...
1218,12KLOXFLS2UL,7efbcc2d3b842,1541696219,2,clickout item,NaN,PH,"Baguio, Philippines",mobile,NaN,"[528971, 6861464, 6454130, 2212472, 9171490, 1...",137|90|46|83|63|136|49|66|73|68|33|46|80|15|53...
1246,15V5VU7OVI6V,1cc3253cf3c79,1541683262,1,clickout item,NaN,BR,"São Pedro da Aldeia, Brazil",mobile,NaN,"[966187, 2711161, 1668351, 4621034, 6819520, 6...",40|45|54|36|29|88|17|22|40|31|34|69|48|56|35|7...
1247,178KXI5C1MQ5,55bc447c86ca0,1541601430,1,clickout item,NaN,BE,"Bollène, France",desktop,NaN,"[626831, 671311, 394576, 4090382]",67|42|38|31|55|99|70|55|55|52|46|100|58|85
1274,192UC0Y4V01B,edd419b4ccc29,1541709047,2,clickout item,NaN,MX,"Puerto Escondido, Mexico",mobile,NaN,"[157952, 157946, 42922, 5160192, 6879856, 2560...",68|52|73|104|51|72|43|47|46|21|46|22|186|44|35...
1283,1EFW4IOR41G9,fbb05a0ea3bc8,1541704832,1,clickout item,NaN,CL,"Puerto Varas, Chile",desktop,NaN,"[1351036, 494711, 1377821, 1356178, 8996556, 8...",103|166|134|112|93|386|227|184|44|70|139|98|57...
1284,1F6SBMYWS704,2e983a3a35994,1541645441,1,clickout item,NaN,TH,"Koh Larn, Thailand",desktop,NaN,"[4198166, 9513722, 2678068, 7837688, 3821172]",145|131|80|144|98
1303,1L8OFJB6FT2L,4a0f0c4edbfca,1541627198,2,clickout item,NaN,NL,"Maastricht, Netherlands",tablet,NaN,"[42292, 3976824, 14218, 131842, 42162, 14452, ...",137|194|108|137|185|177|216|207|390|315|182|23...
1304,1NFTZ9RMO1R2,18f0fa0d6ffef,1541576714,1,clickout item,NaN,RO,"Cluj-Napoca, Romania",desktop,NaN,"[397286, 2170614, 507886, 394836, 2129068, 120...",68|104|66|97|117|97|118|53|64|48|143|62|51|62|...
...,...,...,...,...,...,...,...,...,...,...,...,...
3781067,Y0KON0KCYQ1H,9e35badf1af48,1541693773,2,clickout item,NaN,MX,"San Miguel de Allende, Mexico",mobile,NaN,"[982989, 4487886, 1122161, 1393380, 42810, 395...",69|199|90|64|74|96|148|271|97|105|102|148|66|2...
3781073,Y0MT1AYYH4QB,312819864ea1c,1541655500,3,clickout item,NaN,AU,"Sydney, Australia",mobile,Focus on Distance,"[54803, 14211, 54982, 55093, 14675, 55078, 109...",96|286|250|113|281|120|56|254|192|134|103|353|...
3781074,Y1LNMRR6DDH4,53facf6f24565,1541678512,1,clickout item,NaN,AU,"Perth, Australia",mobile,NaN,"[102475, 54952, 55140, 5203238, 724986, 55018,...",177|190|145|172|121|57|121|159|108|192|142|108...
3781114,Y7F5J5DE4ZZW,eb9fea954b842,1541647539,2,clickout item,NaN,BR,"Manaus, Brazil",desktop,NaN,"[5121950, 106829, 2381212, 722211, 3133052, 12...",88|155|206|150|354|185|248|146|261|2166|99|123...
3781115,Y7J9N59RMS0R,ac663741da9af,1541587155,1,clickout item,NaN,IN,"Madikeri, India",mobile,NaN,"[2603588, 4773682, 4097178, 2661572, 2629176, ...",277|102|95|13|33|97|14|64|44|21|14|70|60|28|31...
3781128,Y9KX0NL700E8,a169e9ba6ce9f,1541596398,5,clickout item,NaN,DE,"Munich, Germany",mobile,Sort by Price,"[3110040, 5344, 132011, 920421, 109525, 5365, ...",36|57|60|69|70|70|70|71|72|72|72|73|74|76|78|8...
3781141,YAVHKU08YB4H,36669e64ce5d4,1541594627,1,clickout item,NaN,BR,"Salvador Bahia, Brazil",mobile,NaN,"[93683, 2519958, 982755, 2432711, 98516, 10936...",29|36|56|56|31|35|36|37|62|96|78|51|56|64|67|3...
3781142,YCD0YTEQGEAA,59380c26dcf19,1541616108,1,clickout item,NaN,EC,"Ambato, Ecuador",desktop,NaN,"[10597634, 2829868]",283|26
3781273,YFQT797MMKUT,44f4e4749e942,1541680658,1,clickout item,NaN,BR,"Olímpia, Brazil",mobile,NaN,"[3921330, 2517193, 4454864, 2795937, 3248056, ...",60|80|127|115|27|49|29|33|65|170|31|45|54|76|3...
3781274,YG00MHZCAVAD,7ac8377f1cf02,1541583013,1,clickout item,NaN,RU,"Ryazan, Russia",mobile,NaN,[3950130],50|26|48
3781275,YG8FYFCJ325A,5d51d8893f2c5,1541695746,1,clickout item,NaN,EC,"Quito, Ecuador",desktop,NaN,"[5109694, 177217, 99150, 177152, 99153, 627801...",59|157|118|42|132|61|91|90|57|113|70|79|132|68...
3781340,YPPDESME3DDT,a4d18b5878928,1541618012,9,clickout item,NaN,BR,"Caldas Novas, Brazil",desktop,Hotel|Resort|4 Star|5 Star|Excellent Rating,"[3248926, 4871050, 1668645, 2828701, 2454120, ...",78|30|41|29|35|53|27|25|32|62|34|58|54|42|34|3...
3781510,YT9L9JPJXIWX,a301d602d7e00,1541610753,1,clickout item,NaN,BR,"Capão da Canoa, Brazil",mobile,NaN,"[4758110, 3954996, 8965332, 3806932, 2812962, ...",27|36|77|40|43|35|53|116|29|34|26|81|22|58|28|...
3781511,YTB80DPXL79J,64454c1037a44,1541697217,1,clickout item,NaN,BR,"Ilha Comprida, Brazil",mobile,NaN,"[2676734, 2811468, 2681772, 2829910, 4538600, ...",55|54|49|75|62|40|58|35|45|34|50|33|35|35
3781536,YZHZ89YNHQZG,1e09eb2d72569,1541609674,1,clickout item,NaN,IT,"Puerto de la Cruz, Spain",mobile,NaN,"[4143556, 15970, 7343, 15973, 7361, 97675, 156...",95|135|82|77|91|85|112|70|71|95|81|66|95|114|7...
3781584,Z3DOMS0LB5VR,9b797a8304c0d,1541636098,3,clickout item,NaN,BR,"Serra, Brazil",mobile,NaN,"[2509802, 2272964]",119|104|117|59|164
3781632,Z4U39CMNA0KC,f10a96cdd9ab6,1541647890,9,clickout item,NaN,IN,"Patiala, India",mobile,Sort by Price,"[4525722, 4637854, 4609710, 4523982, 4601590, ...",5|5|5|5|6|6|7|7|8|8|9|9|9|10|10|10|10|10|10|11...
3781665,Z5OLI4N9BZ58,460a7458419b8,1541587762,1,clickout item,NaN,JP,"Kyoto, Japan",desktop,NaN,"[346866, 103590, 125092, 473596, 2299818, 9393...",132|62|135|131|132|111|139|114|124|111|173|827...
3781666,Z6S5ELLKWH9U,b4cb947d63b06,1541642593,1,clickout item,NaN,NL,"Kralendijk, BES Islands",mobile,NaN,"[6893878, 30595, 5963500, 975701, 4041334, 305...",156|204|83|120|160|362|142|211|75|161|169|99|9...
3781673,Z7H6WZBWLCXT,5d6cc2ee3db46,1541631030,2,clickout item,NaN,BR,"Fortaleza, Brazil",mobile,NaN,"[104802, 97610, 722206, 104888, 109320, 104867...",71|99|98|89|139|70|90|103|115|86|113|89|48|53|...
3781688,Z9GZ0O9E98XH,1694bed3ee9fb,1541667268,1,clickout item,NaN,AU,"Adelaide, Australia",desktop,NaN,"[14848, 1320172, 3505194, 1345404, 55147, 5486...",96|86|89|140|80|95|168|73|46|82|127|210|89|89|...
3781690,ZFD2YAQS3YX4,1e7237d9f35a8,1541709847,2,clickout item,NaN,BR,"São Paulo, Brazil",desktop,NaN,"[104710, 104513, 104912, 104671, 1076986, 4789...",138|365|144|136|183|79|84|457|96|216|104|129|1...
3781709,ZJDPHM5DWJCD,e1b43bf209d50,1541577899,1,clickout item,NaN,BE,"Grindelwald, Switzerland",mobile,NaN,"[15955, 15233, 15953, 1362025, 1008989, 14105,...",134|148|212|239|64|105|126|564|126|564|709|218...
3781741,ZN7BDD39Y83X,929b6ba33334d,1541617907,1,clickout item,NaN,UK,"Glasgow, United Kingdom",mobile,NaN,"[627451, 18512, 5645724, 48117, 152500, 217780...",56|47|45|39|54|36|41|49|37|44|56|53|57|56|39|5...
3781776,ZT722F7KOKI8,66c459fc5f1d5,1541569655,1,clickout item,NaN,MX,"Chetumal, Mexico",mobile,NaN,"[2028173, 2777094, 8405872, 2637405, 1321374, ...",43|42|66|28|51|77|70|82|35|36|62|26|24|37|28|2...
3781780,ZU64EXB7HUSC,a12e64eb21788,1541618644,4,clickout item,NaN,US,"Victoria, Canada",desktop,NaN,"[44679, 44729, 392616, 43974, 44410, 44182, 13...",237|169|126|94|133|186|113|286|117|144|181|99|...
3781788,ZUCX42KNP5CA,911f86ae3cf64,1541678577,8,clickout item,NaN,JP,"Sasebo, Japan",desktop,Sort by Price,"[103524, 1923429, 3568628, 1041996, 1179138, 1...",54|100|108|116|135|154|192|208|216|217|249|269...
3781840,ZVUSADAHBEMO,f5f4f9aa82b44,1541678661,1,clickout item,NaN,DE,"Grainau, Germany",desktop,NaN,"[52072, 51656, 96015, 765928, 5483, 5465, 5470...",146|200|124|99|88|133|112|85|79|95|87|95|95|91...
3782327,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,clickout item,NaN,US,"Holiday City, USA",mobile,NaN,"[364796, 1299248, 4891790, 381296, 1345175, 96...",92|52|92|89|59|275
3782334,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,"[46144, 1345912, 46149, 46119, 895195, 12455, ...",138|138|156|153|128|202|145|137|105|68|133|167...

In [28]:
df_test_for_sub = get_submission_target(df_test)
print(df_test_for_sub.shape)

(253573, 12)

In [30]:
df_test_for_s = df_test_for_sub[~df_test_for_sub['session_id'].isin(count_no_ref_numeric_in_session)]
print(df_test_for_s.shape)

(164612, 12)

In [37]:
df_test_for_s.shape

(164612, 12)

In [ ]:
df_test_for_s.loc[:,'impressions'] = df_test_for_s['impressions'].apply(string_to_array)

In [38]:
df_submission = df_test_for_s.append(df_no_ref)
print(df_submission.shape)

(253573, 12)

In [39]:
df_submission

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
6,004A07DM0IDW,1d688ec168932,1541555799,7,clickout item,NaN,CO,"Santa Marta, Colombia",mobile,NaN,"[2059240, 2033381, 1724779, 127131, 399441, 10...",70|46|48|76|65|65|106|66|87|43|52|44|60|61|50|...
8,009RGHI3G9A3,f05ab0de907e2,1541570940,2,clickout item,NaN,IN,"Nathdwara, India",mobile,NaN,"[10884872, 7065316]",64|28
10,00Y1Z24X8084,26b6d294d66e7,1541651823,2,clickout item,NaN,PH,"Iloilo City, Philippines",mobile,NaN,"[2714480, 4476010, 3843244, 3833012, 9017890, ...",74|14|22|38|55|44|28|34|23|27|12|108|19|21|36|...
15,01V3WDTDM5CU,07628a0f5be0b,1541575643,5,clickout item,NaN,PL,"Wisla, Poland",mobile,Sort by Price,"[3565720, 2947584, 4115018, 2039671, 3836538, ...",16|18|20|21|22|22|28|28|28|30|30|33|33|35|35|3...
61,02AOAVF9PVYH,4a01c3afbc224,1541681278,46,clickout item,NaN,JP,"Yokohama, Japan",desktop,Hotel|Resort|Sort by Price,"[1451247, 559056, 1045096, 1963879, 693596, 19...",80|81|81|82|82|82|83|83|83|85|85|88|88|91|92|9...
109,0339C84S24ET,89171d441a304,1541615683,36,clickout item,NaN,TR,"Antalya, Turkey",mobile,NaN,"[13361, 5647680, 116764, 898719, 8276346, 9168...",185|84|30|19|46|77|123|23|25|25|26|39|73|56|96...
111,0386OH8JDE1Q,e09591d07cdef,1541620536,2,clickout item,NaN,UK,"John o' Groats, United Kingdom",desktop,NaN,"[1193320, 5488246, 3858774, 4552034, 10620372,...",103|88|100|134|109|138|126|86
115,03LTH89QY623,7663406cf586c,1541554183,4,clickout item,NaN,CA,"Koloa, USA",desktop,NaN,"[241961, 906477, 991561, 353701, 1149665, 7725...",287|300|261|197|163|263|262|188|540|283|211|22...
138,03VT0ODUTZB0,725e8adf70e86,1541632490,23,clickout item,NaN,UK,"Warrington, United Kingdom",desktop,NaN,"[109938, 164193, 632366, 1362450, 1070666, 164...",45|67|78|60|58|57|86|68|57|55|148|92|66|55|61|...
314,03XH0JWCWHAM,73f4c417ff730,1541566143,176,clickout item,NaN,MX,"Puebla, Mexico",mobile,Sort By Popularity,"[42692, 5116230, 42876, 4342578, 42864, 314869...",53|181|60|45|96|60|80|59|41|122|50|43|113|48|5...
340,062OG5L9831R,289b34a2bb4dd,1541663105,21,clickout item,NaN,TR,"Sigacik, Turkey",desktop,NaN,"[5828606, 6618430, 7828086, 8474478, 9225478, ...",45|44|51|40|28|50|43|28|26|46|30|27|55|110|44|...
354,06OT6WXN246O,ca92389e5ea65,1541688448,14,clickout item,NaN,KR,"Namhae, South Korea",desktop,NaN,"[4667086, 3152528, 5480450, 4341286, 5601476, ...",132|63|78|115|78|110|117|56|127|78|70|180|133|...
384,08GEUYKFOOPX,83ce8ea2a61b4,1541643155,30,clickout item,NaN,MY,"Malacca, Malaysia",mobile,NaN,"[3818266, 2547593, 3899110, 4599632, 377921, 5...",23|32|27|30|30|38|97|14|53|38|49|47|25|29|17|3...
447,091L4C793B1J,49816a95c986a,1541625659,63,clickout item,NaN,AR,"Bombinhas, Brazil",mobile,NaN,"[2504828, 2578276, 511676, 2344190, 1652507, 3...",135|76|62|93|51|45|75|28|40|76|32|27|50|77|92|...
449,09K0CO8F5AXJ,ccaf5005ee842,1541693719,2,clickout item,NaN,DE,"Leipzig, Germany",desktop,NaN,"[6605, 2270374, 12959, 6576, 1622837, 4122274,...",165|226|189|82|249|109|154|146|68|110|158|188|...
452,09X618WIVTP3,b1935d2a43d5e,1541688108,3,clickout item,NaN,MY,"Genting Highlands, Malaysia",mobile,NaN,"[1120687, 2165594, 5763948, 519501, 595286, 33...",39|76|78|55|87|38|47|143|57|53|21|8|78|17|59|1...
494,09YREZJA9YH3,572801ee070f0,1541688494,42,clickout item,NaN,TR,"Kozakli, Turkey",mobile,NaN,"[2032775, 491891, 1886115, 3877836, 5723470, 4...",27|24|50|37|27|53|56|40|40|18|40|42|25|24|21|4...
510,0A30V2M11MDK,dc8ded19d1781,1541689101,16,clickout item,NaN,NL,"Paris, France",desktop,Hotel Chain|Focus on Distance|Satisfactory Rating,"[362746, 48572, 48885, 49747, 48426, 50136, 85...",78|62|69|74|91|74|77|113|70|79|91|80|91|106|11...
512,0A8YWBYRBRTP,d29141ddbd43f,1541623589,2,clickout item,NaN,CA,"Ottawa, Canada",desktop,NaN,"[43495, 43652, 44038, 43503, 44682, 43765, 433...",109|106|106|119|89|141|103|93|89|93|81|106|126...
546,0CN5A7BJZRGW,0b105be325b12,1541657496,33,clickout item,NaN,IN,"Bengaluru, India",desktop,NaN,"[998041, 1389106, 1400686, 2216204, 2394112, 2...",11|47|23|19|12|8|16|16|23|16|18|19|15|22|103|2...
553,0D1M41K80XJ1,7567cae385981,1541660443,7,clickout item,NaN,HK,"Macau, China",desktop,NaN,"[2269838, 1439759, 211041, 1833415, 1331323, 9...",114|142|188|144|146|104|96|107|135|90|81|137|1...
594,0DHC2FF92LFS,b4b881ddb91e0,1541601665,40,clickout item,NaN,AU,"Lorne, Australia",mobile,NaN,"[109119, 109118, 1018349, 2846590, 1885413, 29...",145|131|108|86|83|222|72|140|111|92|121|32|114...
597,0DJUQ92EQYM0,d2039eb924c5d,1541649689,3,clickout item,NaN,BR,"Águas Claras, Brazil",mobile,NaN,"[3145586, 5157920, 478986, 3993110, 478991, 57...",44|26|30|43|45|37|17|42|17|25|27|22|44|33|22|3...
606,0HQM42M23DRC,b126adad339fe,1541580854,2,clickout item,NaN,ES,"London, United Kingdom",mobile,NaN,"[12688, 12669, 12694, 12695, 12712, 46272, 471...",113|46|136|171|275|83|192|258|83|287|92|114|57...
614,0I20KCPKN010,f7529e581ca06,1541579052,8,clickout item,NaN,IN,"Diu, India",mobile,NaN,"[1401168, 1522957, 6686816, 1133827, 2656700, ...",46|72|52|172|60|60|81|42|36|78|63|42|83|63|37|...
679,0J02N1PV2F7U,5caef301b61c5,1541600100,63,clickout item,NaN,IN,"Jodhpur, India",desktop,NaN,"[7958190, 7938766, 1976583, 4503802, 7533136, ...",25|10|17|9|27|23|26|7|24|25|12|31|6|30|33|35|7...
681,0KUI1NN03SJT,ef3de41013dc9,1541588206,2,clickout item,NaN,UK,"London, United Kingdom",tablet,NaN,"[46462, 8254824, 2529342, 6230236, 6535552, 46...",148|188|102|155|120|91|101|75|86|91|148|256|65...
796,0LDPAF4IYVK4,5862212ab8611,1541641772,114,clickout item,NaN,US,"Orlando, USA",desktop,Hotel|Motel|Very Good Rating|Breakfast Included,"[610931, 9324046, 358946, 8271, 111344, 64693,...",121|244|176|255|119|191|84|206|197|162|114|115
800,0M88URLII445,d70b87505f218,1541613013,4,clickout item,NaN,IN,"Delhi, India",mobile,NaN,"[6453690, 99481, 153200, 930065, 1117713, 1158...",25|101|121|14|41|42|19|25|38|24|51|20|33|31|5|...
806,0MQS09UWZ4TU,d80dc1f57e556,1541616687,5,clickout item,NaN,BR,"Tibau do Sul, Brazil",mobile,NaN,"[513401, 1700081, 479176, 1496061, 1045504, 16...",50|67|41|45|50|58|40|151|42|57|51|55|160|59|11...
...,...,...,...,...,...,...,...,...,...,...,...,...
3781067,Y0KON0KCYQ1H,9e35badf1af48,1541693773,2,clickout item,NaN,MX,"San Miguel de Allende, Mexico",mobile,NaN,"[982989, 4487886, 1122161, 1393380, 42810, 395...",69|199|90|64|74|96|148|271|97|105|102|148|66|2...
3781073,Y0MT1AYYH4QB,312819864ea1c,1541655500,3,clickout item,NaN,AU,"Sydney, Australia",mobile,Focus on Distance,"[54803, 14211, 54982, 55093, 14675, 55078, 109...",96|286|250|113|281|120|56|254|192|134|103|353|...
3781074,Y1LNMRR6DDH4,53facf6f24565,1541678512,1,clickout item,NaN,AU,"Perth, Australia",mobile,NaN,"[102475, 54952, 55140, 5203238, 724986, 55018,...",177|190|145|172|121|57|121|159|108|192|142|108...
3781114,Y7F5J5DE4ZZW,eb9fea954b842,1541647539,2,clickout item,NaN,BR,"Manaus, Brazil",desktop,NaN,"[5121950, 106829, 2381212, 722211, 3133052, 12...",88|155|206|150|354|185|248|146|261|2166|99|123...
3781115,Y7J9N59RMS0R,ac663741da9af,1541587155,1,clickout item,NaN,IN,"Madikeri, India",mobile,NaN,"[2603588, 4773682, 4097178, 2661572, 2629176, ...",277|102|95|13|33|97|14|64|44|21|14|70|60|28|31...
3781128,Y9KX0NL700E8,a169e9ba6ce9f,1541596398,5,clickout item,NaN,DE,"Munich, Germany",mobile,Sort by Price,"[3110040, 5344, 132011, 920421, 109525, 5365, ...",36|57|60|69|70|70|70|71|72|72|72|73|74|76|78|8...
3781141,YAVHKU08YB4H,36669e64ce5d4,1541594627,1,clickout item,NaN,BR,"Salvador Bahia, Brazil",mobile,NaN,"[93683, 2519958, 982755, 2432711, 98516, 10936...",29|36|56|56|31|35|36|37|62|96|78|51|56|64|67|3...
3781142,YCD0YTEQGEAA,59380c26dcf19,1541616108,1,clickout item,NaN,EC,"Ambato, Ecuador",desktop,NaN,"[10597634, 2829868]",283|26
3781273,YFQT797MMKUT,44f4e4749e942,1541680658,1,clickout item,NaN,BR,"Olímpia, Brazil",mobile,NaN,"[3921330, 2517193, 4454864, 2795937, 3248056, ...",60|80|127|115|27|49|29|33|65|170|31|45|54|76|3...
3781274,YG00MHZCAVAD,7ac8377f1cf02,1541583013,1,clickout item,NaN,RU,"Ryazan, Russia",mobile,NaN,[3950130],50|26|48
3781275,YG8FYFCJ325A,5d51d8893f2c5,1541695746,1,clickout item,NaN,EC,"Quito, Ecuador",desktop,NaN,"[5109694, 177217, 99150, 177152, 99153, 627801...",59|157|118|42|132|61|91|90|57|113|70|79|132|68...
3781340,YPPDESME3DDT,a4d18b5878928,1541618012,9,clickout item,NaN,BR,"Caldas Novas, Brazil",desktop,Hotel|Resort|4 Star|5 Star|Excellent Rating,"[3248926, 4871050, 1668645, 2828701, 2454120, ...",78|30|41|29|35|53|27|25|32|62|34|58|54|42|34|3...
3781510,YT9L9JPJXIWX,a301d602d7e00,1541610753,1,clickout item,NaN,BR,"Capão da Canoa, Brazil",mobile,NaN,"[4758110, 3954996, 8965332, 3806932, 2812962, ...",27|36|77|40|43|35|53|116|29|34|26|81|22|58|28|...
3781511,YTB80DPXL79J,64454c1037a44,1541697217,1,clickout item,NaN,BR,"Ilha Comprida, Brazil",mobile,NaN,"[2676734, 2811468, 2681772, 2829910, 4538600, ...",55|54|49|75|62|40|58|35|45|34|50|33|35|35
3781536,YZHZ89YNHQZG,1e09eb2d72569,1541609674,1,clickout item,NaN,IT,"Puerto de la Cruz, Spain",mobile,NaN,"[4143556, 15970, 7343, 15973, 7361, 97675, 156...",95|135|82|77|91|85|112|70|71|95|81|66|95|114|7...
3781584,Z3DOMS0LB5VR,9b797a8304c0d,1541636098,3,clickout item,NaN,BR,"Serra, Brazil",mobile,NaN,"[2509802, 2272964]",119|104|117|59|164
3781632,Z4U39CMNA0KC,f10a96cdd9ab6,1541647890,9,clickout item,NaN,IN,"Patiala, India",mobile,Sort by Price,"[4525722, 4637854, 4609710, 4523982, 4601590, ...",5|5|5|5|6|6|7|7|8|8|9|9|9|10|10|10|10|10|10|11...
3781665,Z5OLI4N9BZ58,460a7458419b8,1541587762,1,clickout item,NaN,JP,"Kyoto, Japan",desktop,NaN,"[346866, 103590, 125092, 473596, 2299818, 9393...",132|62|135|131|132|111|139|114|124|111|173|827...
3781666,Z6S5ELLKWH9U,b4cb947d63b06,1541642593,1,clickout item,NaN,NL,"Kralendijk, BES Islands",mobile,NaN,"[6893878, 30595, 5963500, 975701, 4041334, 305...",156|204|83|120|160|362|142|211|75|161|169|99|9...
3781673,Z7H6WZBWLCXT,5d6cc2ee3db46,1541631030,2,clickout item,NaN,BR,"Fortaleza, Brazil",mobile,NaN,"[104802, 97610, 722206, 104888, 109320, 104867...",71|99|98|89|139|70|90|103|115|86|113|89|48|53|...
3781688,Z9GZ0O9E98XH,1694bed3ee9fb,1541667268,1,clickout item,NaN,AU,"Adelaide, Australia",desktop,NaN,"[14848, 1320172, 3505194, 1345404, 55147, 5486...",96|86|89|140|80|95|168|73|46|82|127|210|89|89|...
3781690,ZFD2YAQS3YX4,1e7237d9f35a8,1541709847,2,clickout item,NaN,BR,"São Paulo, Brazil",desktop,NaN,"[104710, 104513, 104912, 104671, 1076986, 4789...",138|365|144|136|183|79|84|457|96|216|104|129|1...
3781709,ZJDPHM5DWJCD,e1b43bf209d50,1541577899,1,clickout item,NaN,BE,"Grindelwald, Switzerland",mobile,NaN,"[15955, 15233, 15953, 1362025, 1008989, 14105,...",134|148|212|239|64|105|126|564|126|564|709|218...
3781741,ZN7BDD39Y83X,929b6ba33334d,1541617907,1,clickout item,NaN,UK,"Glasgow, United Kingdom",mobile,NaN,"[627451, 18512, 5645724, 48117, 152500, 217780...",56|47|45|39|54|36|41|49|37|44|56|53|57|56|39|5...
3781776,ZT722F7KOKI8,66c459fc5f1d5,1541569655,1,clickout item,NaN,MX,"Chetumal, Mexico",mobile,NaN,"[2028173, 2777094, 8405872, 2637405, 1321374, ...",43|42|66|28|51|77|70|82|35|36|62|26|24|37|28|2...
3781780,ZU64EXB7HUSC,a12e64eb21788,1541618644,4,clickout item,NaN,US,"Victoria, Canada",desktop,NaN,"[44679, 44729, 392616, 43974, 44410, 44182, 13...",237|169|126|94|133|186|113|286|117|144|181|99|...
3781788,ZUCX42KNP5CA,911f86ae3cf64,1541678577,8,clickout item,NaN,JP,"Sasebo, Japan",desktop,Sort by Price,"[103524, 1923429, 3568628, 1041996, 1179138, 1...",54|100|108|116|135|154|192|208|216|217|249|269...
3781840,ZVUSADAHBEMO,f5f4f9aa82b44,1541678661,1,clickout item,NaN,DE,"Grainau, Germany",desktop,NaN,"[52072, 51656, 96015, 765928, 5483, 5465, 5470...",146|200|124|99|88|133|112|85|79|95|87|95|95|91...
3782327,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,clickout item,NaN,US,"Holiday City, USA",mobile,NaN,"[364796, 1299248, 4891790, 381296, 1345175, 96...",92|52|92|89|59|275
3782334,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,clickout item,NaN,IT,"Dublin, Ireland",mobile,NaN,"[46144, 1345912, 46149, 46119, 895195, 12455, ...",138|138|156|153|128|202|145|137|105|68|133|167...

In [41]:
for index, row in df_submission.iterrows():
    df_submission.at[index, 'impressions'] =  " ".join(str(x) for x in row['impressions'])
    
df_submission = df_submission[['user_id','session_id','timestamp','step','impressions']]
df_submission.columns = ['user_id','session_id','timestamp','step','item_recommendations']
#df_submission

,user_id,session_id,timestamp,step,item_recommendations
6,004A07DM0IDW,1d688ec168932,1541555799,7,2059240 2033381 1724779 127131 399441 103357 1...
8,009RGHI3G9A3,f05ab0de907e2,1541570940,2,10884872 7065316
10,00Y1Z24X8084,26b6d294d66e7,1541651823,2,2714480 4476010 3843244 3833012 9017890 198100...
15,01V3WDTDM5CU,07628a0f5be0b,1541575643,5,3565720 2947584 4115018 2039671 3836538 801409...
61,02AOAVF9PVYH,4a01c3afbc224,1541681278,46,1451247 559056 1045096 1963879 693596 1967173 ...
109,0339C84S24ET,89171d441a304,1541615683,36,13361 5647680 116764 898719 8276346 9168 19325...
111,0386OH8JDE1Q,e09591d07cdef,1541620536,2,1193320 5488246 3858774 4552034 10620372 22696...
115,03LTH89QY623,7663406cf586c,1541554183,4,241961 906477 991561 353701 1149665 77258 4943...
138,03VT0ODUTZB0,725e8adf70e86,1541632490,23,109938 164193 632366 1362450 1070666 164220 11...
314,03XH0JWCWHAM,73f4c417ff730,1541566143,176,42692 5116230 42876 4342578 42864 3148690 2123...
340,062OG5L9831R,289b34a2bb4dd,1541663105,21,5828606 6618430 7828086 8474478 9225478 991468...
354,06OT6WXN246O,ca92389e5ea65,1541688448,14,4667086 3152528 5480450 4341286 5601476 397494...
384,08GEUYKFOOPX,83ce8ea2a61b4,1541643155,30,3818266 2547593 3899110 4599632 377921 508851 ...
447,091L4C793B1J,49816a95c986a,1541625659,63,2504828 2578276 511676 2344190 1652507 3242334...
449,09K0CO8F5AXJ,ccaf5005ee842,1541693719,2,6605 2270374 12959 6576 1622837 4122274 195595...
452,09X618WIVTP3,b1935d2a43d5e,1541688108,3,1120687 2165594 5763948 519501 595286 3386520 ...
494,09YREZJA9YH3,572801ee070f0,1541688494,42,2032775 491891 1886115 3877836 5723470 4493250...
510,0A30V2M11MDK,dc8ded19d1781,1541689101,16,362746 48572 48885 49747 48426 50136 85862 496...
512,0A8YWBYRBRTP,d29141ddbd43f,1541623589,2,43495 43652 44038 43503 44682 43765 43359 4361...
546,0CN5A7BJZRGW,0b105be325b12,1541657496,33,998041 1389106 1400686 2216204 2394112 2817576...
553,0D1M41K80XJ1,7567cae385981,1541660443,7,2269838 1439759 211041 1833415 1331323 923995 ...
594,0DHC2FF92LFS,b4b881ddb91e0,1541601665,40,109119 109118 1018349 2846590 1885413 2941498 ...
597,0DJUQ92EQYM0,d2039eb924c5d,1541649689,3,3145586 5157920 478986 3993110 478991 5790206 ...
606,0HQM42M23DRC,b126adad339fe,1541580854,2,12688 12669 12694 12695 12712 46272 47101 4808...
614,0I20KCPKN010,f7529e581ca06,1541579052,8,1401168 1522957 6686816 1133827 2656700 266167...
679,0J02N1PV2F7U,5caef301b61c5,1541600100,63,7958190 7938766 1976583 4503802 7533136 104953...
681,0KUI1NN03SJT,ef3de41013dc9,1541588206,2,46462 8254824 2529342 6230236 6535552 46686 18...
796,0LDPAF4IYVK4,5862212ab8611,1541641772,114,610931 9324046 358946 8271 111344 64693 64553 ...
800,0M88URLII445,d70b87505f218,1541613013,4,6453690 99481 153200 930065 1117713 1158460 18...
806,0MQS09UWZ4TU,d80dc1f57e556,1541616687,5,513401 1700081 479176 1496061 1045504 1627077 ...
...,...,...,...,...,...
3781067,Y0KON0KCYQ1H,9e35badf1af48,1541693773,2,982989 4487886 1122161 1393380 42810 395701 51...
3781073,Y0MT1AYYH4QB,312819864ea1c,1541655500,3,54803 14211 54982 55093 14675 55078 109040 666...
3781074,Y1LNMRR6DDH4,53facf6f24565,1541678512,1,102475 54952 55140 5203238 724986 55018 239695...
3781114,Y7F5J5DE4ZZW,eb9fea954b842,1541647539,2,5121950 106829 2381212 722211 3133052 128468 1...
3781115,Y7J9N59RMS0R,ac663741da9af,1541587155,1,2603588 4773682 4097178 2661572 2629176 387505...
3781128,Y9KX0NL700E8,a169e9ba6ce9f,1541596398,5,3110040 5344 132011 920421 109525 5365 924407 ...
3781141,YAVHKU08YB4H,36669e64ce5d4,1541594627,1,93683 2519958 982755 2432711 98516 109360 4783...
3781142,YCD0YTEQGEAA,59380c26dcf19,1541616108,1,10597634 2829868
3781273,YFQT797MMKUT,44f4e4749e942,1541680658,1,3921330 2517193 4454864 2795937 3248056 268146...
3781274,YG00MHZCAVAD,7ac8377f1cf02,1541583013,1,3950130
3781275,YG8FYFCJ325A,5d51d8893f2c5,1541695746,1,5109694 177217 99150 177152 99153 627801 32225...
3781340,YPPDESME3DDT,a4d18b5878928,1541618012,9,3248926 4871050 1668645 2828701 2454120 123586...
3781510,YT9L9JPJXIWX,a301d602d7e00,1541610753,1,4758110 3954996 8965332 3806932 2812962 838485...
3781511,YTB80DPXL79J,64454c1037a44,1541697217,1,2676734 2811468 2681772 2829910 4538600 265147...
3781536,YZHZ89YNHQZG,1e09eb2d72569,1541609674,1,4143556 15970 7343 15973 7361 97675 15662 9424...
3781584,Z3DOMS0LB5VR,9b797a8304c0d,1541636098,3,2509802 2272964
3781632,Z4U39CMNA0KC,f10a96cdd9ab6,1541647890,9,4525722 4637854 4609710 4523982 4601590 391453...
3781665,Z5OLI4N9BZ58,460a7458419b8,1541587762,1,346866 103590 125092 473596 2299818 939332 818...
3781666,Z6S5ELLKWH9U,b4cb947d63b06,1541642593,1,6893878 30595 5963500 975701 4041334 30589 308...
3781673,Z7H6WZBWLCXT,5d6cc2ee3db46,1541631030,2,104802 97610 722206 104888 109320 104867 10480...
3781688,Z9GZ0O9E98XH,1694bed3ee9fb,1541667268,1,14848 1320172 3505194 1345404 55147 54864 4506...
3781690,ZFD2YAQS3YX4,1e7237d9f35a8,1541709847,2,104710 104513 104912 104671 1076986 478966 104...
3781709,ZJDPHM5DWJCD,e1b43bf209d50,1541577899,1,15955 15233 15953 1362025 1008989 14105 255410...
3781741,ZN7BDD39Y83X,929b6ba33334d,1541617907,1,627451 18512 5645724 48117 152500 2177802 1098...
3781776,ZT722F7KOKI8,66c459fc5f1d5,1541569655,1,2028173 2777094 8405872 2637405 1321374 202780...
3781780,ZU64EXB7HUSC,a12e64eb21788,1541618644,4,44679 44729 392616 43974 44410 44182 1353966 4...
3781788,ZUCX42KNP5CA,911f86ae3cf64,1541678577,8,103524 1923429 3568628 1041996 1179138 1039224...
3781840,ZVUSADAHBEMO,f5f4f9aa82b44,1541678661,1,52072 51656 96015 765928 5483 5465 5470 117981...
3782327,ZYMVSZ5A3KQI,8cd16c29b733b,1541695019,2,364796 1299248 4891790 381296 1345175 9647370
3782334,ZZCM39YKI3NR,6226bde1465e7,1541601178,1,46144 1345912 46149 46119 895195 12455 16674 1...

In [42]:
#df_submission.to_csv("../location_subm.csv", encoding='utf-8', index=False)